//! Browser artifact descriptors for the v2 browser-forensic profiles.
//!
//! These 13 entries use the `browser_` prefix namespace and cover Chrome,
//! Firefox, and Safari artifacts targeted by the browser-forensic workspace.

use super::super::types::{
    ArtifactDescriptor, ArtifactType, DataScope, Decoder, OsScope, TriagePriority,
};

pub(crate) static BROWSER_CHROME_HISTORY: ArtifactDescriptor = ArtifactDescriptor {
    id: "browser_chrome_history",
    name: "Chrome History (browser-forensic)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some("%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\History"),
    scope: DataScope::Mixed,
    os_scope: OsScope::Win7Plus,
    decoder: Decoder::Identity,
    meaning: "Chrome browsing history SQLite database (URLs, visit counts, typed counts).",
    mitre_techniques: &["T1217"],
    fields: &[],
    retention: None,
    triage_priority: TriagePriority::High,
    related_artifacts: &[],
    sources: &["https://forensicswiki.xyz/wiki/index.php?title=Google_Chrome"],
};

pub(crate) static BROWSER_CHROME_COOKIES: ArtifactDescriptor = ArtifactDescriptor {
    id: "browser_chrome_cookies",
    name: "Chrome Cookies (browser-forensic)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some("%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\Network\\Cookies"),
    scope: DataScope::Mixed,
    os_scope: OsScope::Win7Plus,
    decoder: Decoder::Identity,
    meaning: "Chrome cookies SQLite database — session tokens and tracking data.",
    mitre_techniques: &["T1539"],
    fields: &[],
    retention: None,
    triage_priority: TriagePriority::High,
    related_artifacts: &[],
    sources: &["https://forensicswiki.xyz/wiki/index.php?title=Google_Chrome"],
};

pub(crate) static BROWSER_CHROME_DOWNLOADS: ArtifactDescriptor = ArtifactDescriptor {
    id: "browser_chrome_downloads",
    name: "Chrome Downloads (browser-forensic)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some("%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\History"),
    scope: DataScope::Mixed,
    os_scope: OsScope::Win7Plus,
    decoder: Decoder::Identity,
    meaning: "Chrome downloads table within History SQLite database.",
    mitre_techniques: &["T1217"],
    fields: &[],
    retention: None,
    triage_priority: TriagePriority::High,
    related_artifacts: &[],
    sources: &["https://forensicswiki.xyz/wiki/index.php?title=Google_Chrome"],
};

pub(crate) static BROWSER_CHROME_BOOKMARKS: ArtifactDescriptor = ArtifactDescriptor {
    id: "browser_chrome_bookmarks",
    name: "Chrome Bookmarks (browser-forensic)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some("%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\Bookmarks"),
    scope: DataScope::Mixed,
    os_scope: OsScope::Win7Plus,
    decoder: Decoder::Identity,
    meaning: "Chrome bookmarks JSON file.",
    mitre_techniques: &["T1217"],
    fields: &[],
    retention: None,
    triage_priority: TriagePriority::Medium,
    related_artifacts: &[],
    sources: &["https://forensicswiki.xyz/wiki/index.php?title=Google_Chrome"],
};

pub(crate) static BROWSER_CHROME_EXTENSIONS: ArtifactDescriptor = ArtifactDescriptor {
    id: "browser_chrome_extensions",
    name: "Chrome Extensions (browser-forensic)",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some("%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\Extensions"),
    scope: DataScope::Mixed,
    os_scope: OsScope::Win7Plus,
    decoder: Decoder::Identity,
    meaning: "Chrome extensions directory.",
    mitre_techniques: &["T1176"],
    fields: &[],
    retention: None,
    triage_priority: TriagePriority::Medium,
    related_artifacts: &[],
    sources: &["https://forensicswiki.xyz/wiki/index.php?title=Google_Chrome"],
};

pub(crate) static BROWSER_CHROME_LOGIN_DATA_V2: ArtifactDescriptor = ArtifactDescriptor {
    id: "browser_chrome_login_data_v2",
    name: "Chrome Login Data v2 (browser-forensic)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some("%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\Login Data"),
    scope: DataScope::Mixed,
    os_scope: OsScope::Win7Plus,
    decoder: Decoder::Identity,
    meaning: "Chrome saved credentials SQLite database (passwords encrypted with DPAPI/OS keystore).",
    mitre_techniques: &["T1555.003"],
    fields: &[],
    retention: None,
    triage_priority: TriagePriority::Critical,
    related_artifacts: &[],
    sources: &["https://forensicswiki.xyz/wiki/index.php?title=Google_Chrome"],
};

pub(crate) static BROWSER_CHROME_AUTOFILL: ArtifactDescriptor = ArtifactDescriptor {
    id: "browser_chrome_autofill",
    name: "Chrome Autofill (browser-forensic)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some("%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\Web Data"),
    scope: DataScope::Mixed,
    os_scope: OsScope::Win7Plus,
    decoder: Decoder::Identity,
    meaning: "Chrome autofill form data SQLite database.",
    mitre_techniques: &["T1555.003", "T1005"],
    fields: &[],
    retention: None,
    triage_priority: TriagePriority::Medium,
    related_artifacts: &[],
    sources: &["https://forensicswiki.xyz/wiki/index.php?title=Google_Chrome"],
};

pub(crate) static BROWSER_CHROME_CACHE: ArtifactDescriptor = ArtifactDescriptor {
    id: "browser_chrome_cache",
    name: "Chrome Cache (browser-forensic)",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some("%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\Cache"),
    scope: DataScope::Mixed,
    os_scope: OsScope::Win7Plus,
    decoder: Decoder::Identity,
    meaning: "Chrome disk cache directory (Simple Cache format).",
    mitre_techniques: &[],
    fields: &[],
    retention: None,
    triage_priority: TriagePriority::Medium,
    related_artifacts: &[],
    sources: &["https://forensicswiki.xyz/wiki/index.php?title=Google_Chrome"],
};

pub(crate) static BROWSER_CHROME_SESSION: ArtifactDescriptor = ArtifactDescriptor {
    id: "browser_chrome_session",
    name: "Chrome Session (browser-forensic)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some("%LOCALAPPDATA%\\Google\\Chrome\\User Data\\Default\\Sessions"),
    scope: DataScope::Mixed,
    os_scope: OsScope::Win7Plus,
    decoder: Decoder::Identity,
    meaning: "Chrome SNSS session file — open tabs and navigation state.",
    mitre_techniques: &["T1217"],
    fields: &[],
    retention: None,
    triage_priority: TriagePriority::Medium,
    related_artifacts: &[],
    sources: &["https://forensicswiki.xyz/wiki/index.php?title=Google_Chrome"],
};

pub(crate) static BROWSER_FIREFOX_HISTORY: ArtifactDescriptor = ArtifactDescriptor {
    id: "browser_firefox_history",
    name: "Firefox History (browser-forensic)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some("%APPDATA%\\Mozilla\\Firefox\\Profiles\\*.default*\\places.sqlite"),
    scope: DataScope::Mixed,
    os_scope: OsScope::Win7Plus,
    decoder: Decoder::Identity,
    meaning: "Firefox places.sqlite — moz_places and moz_historyvisits tables.",
    mitre_techniques: &["T1217"],
    fields: &[],
    retention: None,
    triage_priority: TriagePriority::High,
    related_artifacts: &[],
    sources: &["https://forensicswiki.xyz/wiki/index.php?title=Mozilla_Firefox"],
};

pub(crate) static BROWSER_FIREFOX_COOKIES: ArtifactDescriptor = ArtifactDescriptor {
    id: "browser_firefox_cookies",
    name: "Firefox Cookies (browser-forensic)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some("%APPDATA%\\Mozilla\\Firefox\\Profiles\\*.default*\\cookies.sqlite"),
    scope: DataScope::Mixed,
    os_scope: OsScope::Win7Plus,
    decoder: Decoder::Identity,
    meaning: "Firefox cookies SQLite database (moz_cookies table — host, name, value, expiry, sameSite flags).",
    mitre_techniques: &["T1539"],
    fields: &[],
    retention: None,
    triage_priority: TriagePriority::High,
    related_artifacts: &[],
    sources: &["https://forensicswiki.xyz/wiki/index.php?title=Mozilla_Firefox"],
};

pub(crate) static BROWSER_FIREFOX_DOWNLOADS: ArtifactDescriptor = ArtifactDescriptor {
    id: "browser_firefox_downloads",
    name: "Firefox Downloads (browser-forensic)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some("%APPDATA%\\Mozilla\\Firefox\\Profiles\\*.default*\\places.sqlite"),
    scope: DataScope::Mixed,
    os_scope: OsScope::Win7Plus,
    decoder: Decoder::Identity,
    meaning: "Firefox downloads stored as moz_annos annotations in places.sqlite.",
    mitre_techniques: &["T1217"],
    fields: &[],
    retention: None,
    triage_priority: TriagePriority::High,
    related_artifacts: &[],
    sources: &["https://forensicswiki.xyz/wiki/index.php?title=Mozilla_Firefox"],
};

pub(crate) static BROWSER_SAFARI_HISTORY: ArtifactDescriptor = ArtifactDescriptor {
    id: "browser_safari_history",
    name: "Safari History (browser-forensic)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some("~/Library/Safari/History.db"),
    scope: DataScope::Mixed,
    os_scope: OsScope::MacOS,
    decoder: Decoder::Identity,
    meaning: "Safari History.db — history_items, history_visits, history_tombstones.",
    mitre_techniques: &["T1217"],
    fields: &[],
    retention: None,
    triage_priority: TriagePriority::High,
    related_artifacts: &[],
    sources: &["https://forensicswiki.xyz/wiki/index.php?title=Apple_Safari"],
};
