//! Extended Linux artifact descriptors.
//!
//! Sources: Velociraptor Linux artifacts, ForensicArtifacts/artifacts (linux.yaml),
//! SANS FOR508, auditd documentation, Docker/container forensics resources.

#![allow(clippy::too_many_lines)]

use super::super::types::{
    ArtifactDescriptor, ArtifactType, DataScope, Decoder, FieldSchema, OsScope, TriagePriority,
    ValueType,
};

pub(crate) static LINUX_AUDITD_LOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_auditd_log",
    name: "Auditd Log",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/var/log/audit/audit.log"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Linux Audit daemon log recording syscall-level events: file access, process execution (execve), privilege escalation, network connections, and authentication. The highest-fidelity forensic source on Linux when configured — provides a comprehensive record equivalent to Sysmon on Windows.",
    mitre_techniques: &["T1562.001", "T1059", "T1078"],
    fields: &[
        FieldSchema { name: "type", value_type: ValueType::Text, description: "Audit record type (SYSCALL, EXECVE, etc.)", is_uid_component: true },
        FieldSchema { name: "pid", value_type: ValueType::UnsignedInt, description: "Process ID", is_uid_component: false },
        FieldSchema { name: "comm", value_type: ValueType::Text, description: "Command name", is_uid_component: false },
        FieldSchema { name: "exe", value_type: ValueType::Text, description: "Executable path", is_uid_component: false },
    ],
    retention: Some("Rotated by logrotate; retain_num and max_log_file configurable"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["linux_auth_log", "linux_syslog"],
    sources: &[
        "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/chap-system_auditing",
        "https://attack.mitre.org/techniques/T1562/001/",
    ],
};

pub(crate) static LINUX_AUDIT_RULES: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_audit_rules",
    name: "Auditd Rules Configuration",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/etc/audit/rules.d/"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Active auditd ruleset defining what syscalls and file accesses are monitored. Reviewing rules reveals coverage gaps and attacker-planted rule deletions that silently disable monitoring of specific activity.",
    mitre_techniques: &["T1562.001"],
    fields: &[FieldSchema { name: "rule", value_type: ValueType::Text, description: "Audit rule definition", is_uid_component: true }],
    retention: Some("Persistent configuration"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_auditd_log"],
    sources: &["https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/chap-system_auditing"],
};

pub(crate) static LINUX_SYSLOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_syslog",
    name: "Syslog",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/var/log/syslog"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Main system log on Debian/Ubuntu aggregating messages from most daemons (cron, NetworkManager, rsyslogd, kernel, etc.). Broad-spectrum timeline reconstruction source — often the first log checked in Linux IR.",
    mitre_techniques: &["T1562.002"],
    fields: &[
        FieldSchema { name: "facility", value_type: ValueType::Text, description: "Syslog facility (auth, kern, daemon, etc.)", is_uid_component: false },
        FieldSchema { name: "message", value_type: ValueType::Text, description: "Log message body", is_uid_component: true },
    ],
    retention: Some("Rotated weekly; 4 rotations kept by default"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_auth_log", "linux_journal_dir"],
    sources: &["https://www.sans.org/blog/linux-forensics-from-basic-to-in-depth-evidence-collection/"],
};

pub(crate) static LINUX_MESSAGES_LOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_messages_log",
    name: "Messages Log (RHEL/CentOS)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/var/log/messages"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Main system log on RHEL/CentOS/Fedora (equivalent to /var/log/syslog on Debian). Contains daemon messages, hardware events, and network activity. Primary starting point for Linux IR on Red Hat-family systems.",
    mitre_techniques: &["T1562.002"],
    fields: &[FieldSchema { name: "message", value_type: ValueType::Text, description: "Log message body", is_uid_component: true }],
    retention: Some("Rotated; 4 rotations kept"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_secure_log", "linux_journal_dir"],
    sources: &["https://www.sans.org/blog/linux-forensics-from-basic-to-in-depth-evidence-collection/"],
};

pub(crate) static LINUX_SECURE_LOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_secure_log",
    name: "Secure Log (RHEL/CentOS authentication)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/var/log/secure"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Authentication and authorization log on RHEL/CentOS/Fedora (equivalent to auth.log on Debian). Contains su, sudo, sshd, and PAM events. Primary source for privilege escalation and lateral movement analysis on Red Hat-family systems.",
    mitre_techniques: &["T1078", "T1110", "T1021.004"],
    fields: &[
        FieldSchema { name: "process", value_type: ValueType::Text, description: "Process generating the auth event", is_uid_component: true },
        FieldSchema { name: "message", value_type: ValueType::Text, description: "Authentication event message", is_uid_component: false },
    ],
    retention: Some("Rotated; 4 rotations kept"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["linux_auditd_log", "linux_journal_dir"],
    sources: &["https://www.sans.org/blog/linux-forensics-from-basic-to-in-depth-evidence-collection/"],
};

pub(crate) static LINUX_APACHE_ACCESS_LOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_apache_access_log",
    name: "Apache HTTP Server Access Log",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/var/log/apache2/access.log"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Apache access log recording client IP, request method, URI, response code, and user-agent. Critical for web attack investigation: SQL injection, LFI/RFI, webshell access, C2 beaconing, and data exfiltration via HTTP.",
    mitre_techniques: &["T1190", "T1505.003", "T1071.001"],
    fields: &[
        FieldSchema { name: "client_ip", value_type: ValueType::Text, description: "Client IP address", is_uid_component: true },
        FieldSchema { name: "request", value_type: ValueType::Text, description: "HTTP method + URI + protocol", is_uid_component: false },
        FieldSchema { name: "status_code", value_type: ValueType::UnsignedInt, description: "HTTP response status code", is_uid_component: false },
        FieldSchema { name: "user_agent", value_type: ValueType::Text, description: "Client User-Agent header", is_uid_component: false },
    ],
    retention: Some("Rotated weekly; configurable"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["linux_nginx_access_log"],
    sources: &[
        "https://attack.mitre.org/techniques/T1190/",
        "https://www.sans.org/blog/web-server-log-analysis-for-incident-responders/",
    ],
};

pub(crate) static LINUX_APACHE_ERROR_LOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_apache_error_log",
    name: "Apache HTTP Server Error Log",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/var/log/apache2/error.log"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Apache error log showing server-side errors, mod_security alerts, and failed request details. Reveals exploitation attempts that generate server-side exceptions — stack traces may expose vulnerable code paths.",
    mitre_techniques: &["T1190"],
    fields: &[FieldSchema { name: "error_message", value_type: ValueType::Text, description: "Error message and stack trace", is_uid_component: true }],
    retention: Some("Rotated weekly"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_apache_access_log"],
    sources: &["https://attack.mitre.org/techniques/T1190/"],
};

pub(crate) static LINUX_NGINX_ACCESS_LOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_nginx_access_log",
    name: "Nginx Access Log",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/var/log/nginx/access.log"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Nginx web server access log. Same forensic value as Apache access log; critical for reverse proxy and web application attack investigation. Also covers nginx acting as API gateway or load balancer for containerized apps.",
    mitre_techniques: &["T1190", "T1505.003", "T1071.001"],
    fields: &[
        FieldSchema { name: "client_ip", value_type: ValueType::Text, description: "Client IP address", is_uid_component: true },
        FieldSchema { name: "request", value_type: ValueType::Text, description: "HTTP request line", is_uid_component: false },
        FieldSchema { name: "status_code", value_type: ValueType::UnsignedInt, description: "HTTP response status code", is_uid_component: false },
    ],
    retention: Some("Rotated; configurable"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["linux_apache_access_log"],
    sources: &["https://attack.mitre.org/techniques/T1190/"],
};

pub(crate) static LINUX_FAIL2BAN_LOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_fail2ban_log",
    name: "Fail2Ban Log",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/var/log/fail2ban.log"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Fail2ban action log recording IP addresses banned for repeated authentication failures. Shows brute-force attack source IPs and ban/unban events — unban events may indicate attacker manipulation of fail2ban rules.",
    mitre_techniques: &["T1110"],
    fields: &[
        FieldSchema { name: "banned_ip", value_type: ValueType::Text, description: "IP address banned", is_uid_component: true },
        FieldSchema { name: "jail", value_type: ValueType::Text, description: "Fail2ban jail that triggered the ban", is_uid_component: false },
    ],
    retention: Some("Rotated"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_auth_log", "linux_secure_log"],
    sources: &["https://attack.mitre.org/techniques/T1110/"],
};

pub(crate) static LINUX_DPKG_LOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_dpkg_log",
    name: "DPKG Package Manager Log",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/var/log/dpkg.log"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Debian package manager log recording all install/upgrade/remove/purge operations with precise timestamps. Establishes software installation timeline — reveals attacker-installed tools, backdoored packages, or cleanup attempts.",
    mitre_techniques: &["T1072", "T1195.002"],
    fields: &[
        FieldSchema { name: "package_name", value_type: ValueType::Text, description: "Package name", is_uid_component: true },
        FieldSchema { name: "action", value_type: ValueType::Text, description: "install/upgrade/remove/purge", is_uid_component: false },
        FieldSchema { name: "version", value_type: ValueType::Text, description: "Package version", is_uid_component: false },
    ],
    retention: Some("Rotated monthly; 12 months typically kept"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_apt_hooks"],
    sources: &["https://attack.mitre.org/techniques/T1072/"],
};

pub(crate) static LINUX_RPM_DB: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_rpm_db",
    name: "RPM Package Database",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/var/lib/rpm/Packages"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Berkeley DB / SQLite database of all installed RPM packages with install timestamps, file checksums, and signatories. Queried with `rpm -qa --last` to reconstruct package installation timeline on RHEL/CentOS systems.",
    mitre_techniques: &["T1072", "T1195.002"],
    fields: &[
        FieldSchema { name: "package_name", value_type: ValueType::Text, description: "RPM package name", is_uid_component: true },
        FieldSchema { name: "install_time", value_type: ValueType::Timestamp, description: "Package installation timestamp", is_uid_component: false },
    ],
    retention: Some("Updated on install/remove; reflects current state"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_messages_log"],
    sources: &["https://attack.mitre.org/techniques/T1072/"],
};

pub(crate) static LINUX_SELINUX_CONFIG: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_selinux_config",
    name: "SELinux Configuration",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/etc/selinux/config"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "SELinux mode configuration (Enforcing/Permissive/Disabled). An attacker who sets SELINUX=permissive or disabled removes mandatory access control enforcement — this file persists the change across reboots and is a clear indicator of defense evasion.",
    mitre_techniques: &["T1562"],
    fields: &[FieldSchema { name: "selinux_mode", value_type: ValueType::Text, description: "SELinux mode (enforcing/permissive/disabled)", is_uid_component: true }],
    retention: Some("Persistent"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["linux_auditd_log"],
    sources: &["https://attack.mitre.org/techniques/T1562/"],
};

pub(crate) static LINUX_APPARMOR_PROFILES: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_apparmor_profiles",
    name: "AppArmor Profiles",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/etc/apparmor.d/"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "AppArmor mandatory access control profiles for confined processes. Attacker modification of profiles can silently grant confined processes expanded file, network, or capability permissions — effective defense evasion on Ubuntu/Debian systems.",
    mitre_techniques: &["T1562"],
    fields: &[FieldSchema { name: "profile_name", value_type: ValueType::Text, description: "AppArmor profile name (usually process path)", is_uid_component: true }],
    retention: Some("Persistent configuration"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_auditd_log"],
    sources: &["https://attack.mitre.org/techniques/T1562/"],
};

pub(crate) static LINUX_IPTABLES_RULES: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_iptables_rules",
    name: "Persisted iptables Rules (IPv4)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/etc/iptables/rules.v4"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Persisted IPv4 iptables ruleset (Debian/Ubuntu). Reveals firewall configuration including port redirections, ACCEPT/DROP rules, and logging targets. Attacker modification can open ports for C2 reverse shells or disable egress filtering.",
    mitre_techniques: &["T1562.004"],
    fields: &[FieldSchema { name: "rule", value_type: ValueType::Text, description: "iptables rule definition", is_uid_component: true }],
    retention: Some("Persistent"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_nftables_conf"],
    sources: &["https://attack.mitre.org/techniques/T1562/004/"],
};

pub(crate) static LINUX_NFTABLES_CONF: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_nftables_conf",
    name: "nftables Firewall Configuration",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/etc/nftables.conf"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "nftables firewall configuration (modern replacement for iptables on RHEL 8+/Debian 10+). Modification reveals firewall tampering for defense evasion or lateral movement facilitation.",
    mitre_techniques: &["T1562.004"],
    fields: &[FieldSchema { name: "rule", value_type: ValueType::Text, description: "nftables rule definition", is_uid_component: true }],
    retention: Some("Persistent"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_iptables_rules"],
    sources: &["https://attack.mitre.org/techniques/T1562/004/"],
};

pub(crate) static LINUX_HOSTS_FILE: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_hosts_file",
    name: "/etc/hosts (static DNS overrides)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/etc/hosts"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Static DNS resolution table. Attacker modification redirects domain lookups (e.g., security update servers) to attacker-controlled IPs, enabling DNS hijacking for credential harvesting, C2, or blocking security tool updates.",
    mitre_techniques: &["T1565.001", "T1584"],
    fields: &[
        FieldSchema { name: "ip_address", value_type: ValueType::Text, description: "IP address", is_uid_component: true },
        FieldSchema { name: "hostname", value_type: ValueType::Text, description: "Hostname(s) mapped to IP", is_uid_component: false },
    ],
    retention: Some("Persistent"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_resolv_conf"],
    sources: &["https://attack.mitre.org/techniques/T1565/001/"],
};

pub(crate) static LINUX_RESOLV_CONF: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_resolv_conf",
    name: "/etc/resolv.conf (DNS resolver config)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/etc/resolv.conf"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "DNS resolver configuration pointing to nameserver IPs. Modification to point to an attacker-controlled DNS server enables DNS hijacking and traffic interception — all hostname resolution goes through the malicious resolver.",
    mitre_techniques: &["T1565.001"],
    fields: &[FieldSchema { name: "nameserver", value_type: ValueType::Text, description: "DNS server IP address", is_uid_component: true }],
    retention: Some("Persistent; may be overwritten by NetworkManager/dhclient"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_hosts_file"],
    sources: &["https://attack.mitre.org/techniques/T1565/001/"],
};

pub(crate) static LINUX_PROC_MODULES: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_proc_modules",
    name: "/proc/modules (loaded kernel modules)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/proc/modules"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Live list of loaded kernel modules with addresses and reference counts. Rootkits often load as kernel modules — this file (during live response) reveals loaded modules including those hidden from lsmod via /proc manipulation.",
    mitre_techniques: &["T1014", "T1547.006"],
    fields: &[
        FieldSchema { name: "module_name", value_type: ValueType::Text, description: "Kernel module name", is_uid_component: true },
        FieldSchema { name: "size", value_type: ValueType::UnsignedInt, description: "Module size in bytes", is_uid_component: false },
    ],
    retention: Some("Live kernel state — volatile"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["linux_modprobe_d", "linux_journal_dir"],
    sources: &[
        "https://attack.mitre.org/techniques/T1014/",
        "https://attack.mitre.org/techniques/T1547/006/",
    ],
};

pub(crate) static LINUX_MODPROBE_D: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_modprobe_d",
    name: "modprobe.d Configuration (module loading hooks)",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/etc/modprobe.d/"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Kernel module configuration directory. Persistence via `install` directives causes a malicious binary to execute whenever a legitimate module is loaded — effective module hijacking that survives reboots and appears as normal hardware activity.",
    mitre_techniques: &["T1547.006", "T1574.006"],
    fields: &[FieldSchema { name: "directive", value_type: ValueType::Text, description: "modprobe configuration directive", is_uid_component: true }],
    retention: Some("Persistent"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_proc_modules", "linux_modules_load_d"],
    sources: &["https://attack.mitre.org/techniques/T1574/006/"],
};

pub(crate) static LINUX_DOCKER_CONTAINER_LOGS: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_docker_container_logs",
    name: "Docker Container Logs and State",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/var/lib/docker/containers/"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Docker container runtime data including per-container JSON log files (`*-json.log`), configuration, network settings, and state. Reveals container activity, volume mounts, environment variables, and exposed ports for containerized malware or compromised workloads.",
    mitre_techniques: &["T1610", "T1611"],
    fields: &[
        FieldSchema { name: "container_id", value_type: ValueType::Text, description: "Container ID (directory name prefix)", is_uid_component: true },
        FieldSchema { name: "image", value_type: ValueType::Text, description: "Container image name and tag", is_uid_component: false },
    ],
    retention: Some("Persists until container and logs are removed"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_docker_daemon_json"],
    sources: &[
        "https://attack.mitre.org/techniques/T1610/",
        "https://www.sans.org/blog/container-forensics/",
    ],
};

pub(crate) static LINUX_DOCKER_DAEMON_JSON: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_docker_daemon_json",
    name: "Docker Daemon Configuration",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/etc/docker/daemon.json"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Docker daemon configuration. Modification can enable insecure registries, disable content trust, expose the Docker API socket via TCP (unauthenticated), or configure privileged containers — all high-value attacker persistence and escalation techniques.",
    mitre_techniques: &["T1610", "T1562"],
    fields: &[FieldSchema { name: "config_key", value_type: ValueType::Text, description: "Configuration parameter", is_uid_component: true }],
    retention: Some("Persistent"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_docker_container_logs"],
    sources: &["https://attack.mitre.org/techniques/T1610/"],
};

pub(crate) static LINUX_COREDUMP_DIR: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_coredump_dir",
    name: "systemd Coredump Storage",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/var/lib/systemd/coredump/"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "systemd coredump storage for crashed processes. Process memory dumps preserved here can contain in-memory secrets (decryption keys, plaintext credentials), decrypted data, and evidence of exploited processes — valuable but often overlooked.",
    mitre_techniques: &["T1005"],
    fields: &[
        FieldSchema { name: "process_name", value_type: ValueType::Text, description: "Crashed process name", is_uid_component: true },
        FieldSchema { name: "signal", value_type: ValueType::UnsignedInt, description: "Signal that caused the crash", is_uid_component: false },
    ],
    retention: Some("Kept up to configured size limit"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["linux_journal_dir"],
    sources: &["https://systemd.io/COREDUMP/"],
};

pub(crate) static LINUX_LOGROTATE_D: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_logrotate_d",
    name: "Logrotate Configuration Fragments",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/etc/logrotate.d/"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Per-service log rotation configuration fragments. Attacker modification can reduce retention periods, disable compression, or shred rotated logs — anti-forensic evidence that silently destroys log history.",
    mitre_techniques: &["T1070"],
    fields: &[FieldSchema { name: "config_file", value_type: ValueType::Text, description: "Service-specific logrotate config", is_uid_component: true }],
    retention: Some("Persistent configuration"),
    triage_priority: TriagePriority::Medium,
    related_artifacts: &["linux_syslog", "linux_auth_log"],
    sources: &["https://attack.mitre.org/techniques/T1070/"],
};

pub(crate) static LINUX_SNAP_PACKAGES: ArtifactDescriptor = ArtifactDescriptor {
    id: "linux_snap_packages",
    name: "Installed Snap Packages",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,    file_path: Some("/var/lib/snapd/snaps/"),
    scope: DataScope::System,
    os_scope: OsScope::Linux,
    decoder: Decoder::Identity,
    meaning: "Installed Snap packages (squashfs images). Snap installs bypass traditional package managers and may leave no dpkg/rpm audit trail — reveals snap-installed software including attacker tools that evade package-log-based detection.",
    mitre_techniques: &["T1072"],
    fields: &[FieldSchema { name: "snap_name", value_type: ValueType::Text, description: "Snap package name and revision", is_uid_component: true }],
    retention: Some("Retained until snap is removed"),
    triage_priority: TriagePriority::Medium,
    related_artifacts: &["linux_dpkg_log"],
    sources: &["https://attack.mitre.org/techniques/T1072/"],
};
