//! Extended Windows file and directory artifact descriptors — Phase 2.
//!
//! Sources: KAPE targets (EricZimmerman/KapeFiles), Velociraptor artifact definitions,
//! SANS FOR508, BlueTeamLabs, DFIR.blog, 13cubed research.

#![allow(clippy::too_many_lines)]

use super::super::types::{
    ArtifactDescriptor, ArtifactType, DataScope, Decoder, FieldSchema, OsScope, TriagePriority,
    ValueType,
};

// ── Browser History ───────────────────────────────────────────────────────────

pub(crate) static CHROME_HISTORY: ArtifactDescriptor = ArtifactDescriptor {
    id: "chrome_history",
    name: "Chrome Browsing History (SQLite)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Local\Google\Chrome\User Data\*\History"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "SQLite database containing Chrome browsing history, downloads, and search queries. Key tables: urls (visited sites with timestamps), downloads (file downloads with source URL and target path), keyword_search_terms (typed search queries). Malware distribution via browser and C2 beacon URLs appear here.",
    mitre_techniques: &["T1217"],
    fields: &[
        FieldSchema { name: "url", value_type: ValueType::Text, description: "Visited URL", is_uid_component: true },
        FieldSchema { name: "visit_time", value_type: ValueType::Timestamp, description: "Visit timestamp (WebKit microseconds)", is_uid_component: false },
        FieldSchema { name: "title", value_type: ValueType::Text, description: "Page title at visit time", is_uid_component: false },
    ],
    retention: Some("No automatic limit; grows until profile cleared"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["chrome_login_data", "chrome_web_data"],
    sources: &[
        "https://attack.mitre.org/techniques/T1217/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/Chrome.tkape",
        "https://www.sans.org/blog/google-chrome-forensics/",
        "https://13cubed.com/downloads/Windows_Forensic_Analysis_Poster.pdf",
    ],
};

pub(crate) static CHROME_WEB_DATA: ArtifactDescriptor = ArtifactDescriptor {
    id: "chrome_web_data",
    name: "Chrome Web Data (SQLite)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Local\Google\Chrome\User Data\*\Web Data"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "SQLite database storing Chrome autofill form data, saved payment cards (DPAPI-encrypted), and search engine history. Reveals identifiers (names, addresses, phone numbers) typed into web forms even after browsing history is cleared.",
    mitre_techniques: &["T1555.003"],
    fields: &[
        FieldSchema { name: "name", value_type: ValueType::Text, description: "Autofill field name", is_uid_component: true },
        FieldSchema { name: "value", value_type: ValueType::Text, description: "Autofill field value", is_uid_component: false },
    ],
    retention: Some("Persists until profile cleared"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["chrome_history", "chrome_login_data"],
    sources: &[
        "https://attack.mitre.org/techniques/T1555/003/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/Chrome.tkape",
        "https://www.sans.org/blog/google-chrome-forensics/",
    ],
};

pub(crate) static EDGE_CHROMIUM_HISTORY: ArtifactDescriptor = ArtifactDescriptor {
    id: "edge_chromium_history",
    name: "Edge (Chromium) Browsing History (SQLite)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Local\Microsoft\Edge\User Data\*\History"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "SQLite database with Edge Chromium browsing history. Identical schema to Chrome History (same Chromium codebase). Critical on enterprise networks where Edge is the corporate browser and may hold intranet portal access and SharePoint navigation.",
    mitre_techniques: &["T1217"],
    fields: &[
        FieldSchema { name: "url", value_type: ValueType::Text, description: "Visited URL", is_uid_component: true },
        FieldSchema { name: "visit_time", value_type: ValueType::Timestamp, description: "Visit timestamp (WebKit microseconds)", is_uid_component: false },
    ],
    retention: Some("No automatic limit; grows until profile cleared"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["edge_chromium_login_data", "chrome_history"],
    sources: &[
        "https://attack.mitre.org/techniques/T1217/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/MicrosoftEdge.tkape",
        "https://www.sans.org/blog/microsoft-edge-forensics/",
    ],
};

pub(crate) static EDGE_CHROMIUM_LOGIN_DATA: ArtifactDescriptor = ArtifactDescriptor {
    id: "edge_chromium_login_data",
    name: "Edge (Chromium) Login Data (SQLite)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Local\Microsoft\Edge\User Data\*\Login Data"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "SQLite database with DPAPI-encrypted saved credentials from Edge (Chromium). Same schema as Chrome Login Data. On managed corporate devices, Edge may store SSO credentials for internal applications, making this high-value for lateral movement intelligence.",
    mitre_techniques: &["T1555.003"],
    fields: &[
        FieldSchema { name: "origin_url", value_type: ValueType::Text, description: "URL the credential is for", is_uid_component: true },
        FieldSchema { name: "username_value", value_type: ValueType::Text, description: "Stored username", is_uid_component: false },
    ],
    retention: Some("Persists until credential cleared or profile deleted"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["edge_chromium_history", "dpapi_masterkey_user"],
    sources: &[
        "https://attack.mitre.org/techniques/T1555/003/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/MicrosoftEdge.tkape",
    ],
};

pub(crate) static FIREFOX_PLACES: ArtifactDescriptor = ArtifactDescriptor {
    id: "firefox_places",
    name: "Firefox places.sqlite (History + Bookmarks)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\Mozilla\Firefox\Profiles\*\places.sqlite"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Core Firefox history and bookmarks SQLite database. Tables: moz_places (all visited URLs with frecency score), moz_historyvisits (timestamped visit records with transition types), moz_bookmarks (saved bookmarks). Transition type 0=typed, 1=clicked link — distinguishes deliberate navigation from passive redirects.",
    mitre_techniques: &["T1217"],
    fields: &[
        FieldSchema { name: "url", value_type: ValueType::Text, description: "Visited URL", is_uid_component: true },
        FieldSchema { name: "last_visit_date", value_type: ValueType::Timestamp, description: "Last visit timestamp (Unix microseconds)", is_uid_component: false },
        FieldSchema { name: "visit_count", value_type: ValueType::UnsignedInt, description: "Total number of visits", is_uid_component: false },
    ],
    retention: Some("No automatic limit; grows until profile cleared"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["firefox_form_history", "firefox_session_restore", "firefox_logins"],
    sources: &[
        "https://attack.mitre.org/techniques/T1217/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/Firefox.tkape",
        "https://www.sans.org/blog/firefox-history-and-what-it-tells-you/",
        "https://nicoleibrahim.com/mozilla-firefox-forensics/",
    ],
};

pub(crate) static FIREFOX_FORM_HISTORY: ArtifactDescriptor = ArtifactDescriptor {
    id: "firefox_form_history",
    name: "Firefox formhistory.sqlite",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\Mozilla\Firefox\Profiles\*\formhistory.sqlite"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Firefox autocomplete form-field history database. Records text typed into web form fields (search boxes, login fields, input boxes) with timestamps and usage counts. Reveals search terms, usernames, and any text ever typed into web forms in Firefox.",
    mitre_techniques: &["T1217"],
    fields: &[
        FieldSchema { name: "fieldname", value_type: ValueType::Text, description: "HTML form field name", is_uid_component: true },
        FieldSchema { name: "value", value_type: ValueType::Text, description: "Text typed into the field", is_uid_component: false },
    ],
    retention: Some("Entries older than 180 days removed automatically"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["firefox_places", "firefox_logins"],
    sources: &[
        "https://attack.mitre.org/techniques/T1217/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/Firefox.tkape",
        "https://nicoleibrahim.com/mozilla-firefox-forensics/",
    ],
};

pub(crate) static FIREFOX_SESSION_RESTORE: ArtifactDescriptor = ArtifactDescriptor {
    id: "firefox_session_restore",
    name: "Firefox sessionstore.jsonlz4 (Session Restore)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\Mozilla\Firefox\Profiles\*\sessionstore.jsonlz4"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "LZ4-compressed JSON snapshot of all open Firefox tabs at last session close. Contains full URLs, scroll positions, and POST data for in-progress forms. Provides evidence of browser state at crash/shutdown — invaluable when history has been cleared but session was not manually saved.",
    mitre_techniques: &["T1217"],
    fields: &[
        FieldSchema { name: "url", value_type: ValueType::Text, description: "URL of open tab at session close", is_uid_component: true },
        FieldSchema { name: "title", value_type: ValueType::Text, description: "Tab title at session close", is_uid_component: false },
    ],
    retention: Some("Overwritten on each browser restart; previous version in sessionstore-backups/"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["firefox_places", "firefox_form_history"],
    sources: &[
        "https://attack.mitre.org/techniques/T1217/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/Firefox.tkape",
        "https://nicoleibrahim.com/mozilla-firefox-forensics/",
    ],
};

// ── PowerShell ────────────────────────────────────────────────────────────────

pub(crate) static PSREADLINE_HISTORY: ArtifactDescriptor = ArtifactDescriptor {
    id: "psreadline_history",
    name: "PSReadLine Console History (User)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Plain-text file of all interactive PowerShell commands typed in the console, one command per line. Persists across sessions. Critical for attacker TTP reconstruction — commands including credential harvesting, lateral movement, and C2 beacon setup appear verbatim with no truncation.",
    mitre_techniques: &["T1059.001"],
    fields: &[
        FieldSchema { name: "command", value_type: ValueType::Text, description: "PowerShell command entered interactively", is_uid_component: true },
    ],
    retention: Some("Default 4096 lines; configurable via $MaximumHistoryCount"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["psreadline_history_system", "powershell_history", "evtx_powershell"],
    sources: &[
        "https://attack.mitre.org/techniques/T1059/001/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/PowerShellConsole.tkape",
        "https://www.sans.org/blog/powershell-forensics-auditing/",
        "https://13cubed.com/downloads/Windows_Forensic_Analysis_Poster.pdf",
    ],
};

pub(crate) static PSREADLINE_HISTORY_SYSTEM: ArtifactDescriptor = ArtifactDescriptor {
    id: "psreadline_history_system",
    name: "PSReadLine Console History (SYSTEM account)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Windows\System32\config\systemprofile\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "PSReadLine history for the SYSTEM account. Attackers who escalate to SYSTEM and run PowerShell interactively leave commands here. Especially relevant for scheduled task abuse, WMI persistence scripts run as SYSTEM, and services spawning cmd/PS shells.",
    mitre_techniques: &["T1059.001"],
    fields: &[
        FieldSchema { name: "command", value_type: ValueType::Text, description: "PowerShell command entered interactively as SYSTEM", is_uid_component: true },
    ],
    retention: Some("Default 4096 lines; configurable via $MaximumHistoryCount"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["psreadline_history", "evtx_powershell", "evtx_task_scheduler"],
    sources: &[
        "https://attack.mitre.org/techniques/T1059/001/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/PowerShellConsole.tkape",
        "https://www.sans.org/blog/powershell-forensics-auditing/",
    ],
};

pub(crate) static POWERSHELL_TRANSCRIPTS: ArtifactDescriptor = ArtifactDescriptor {
    id: "powershell_transcripts",
    name: "PowerShell Transcript Logs",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\Documents"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "PowerShell transcript files (PowerShell_transcript.*.txt) generated when script block transcription is enabled via Group Policy or $Transcript. Contain timestamped full session output including command output — richer than PSReadLine history. Filenames include hostname and datetime. Malware cleanup operations often fail to delete these.",
    mitre_techniques: &["T1059.001"],
    fields: &[
        FieldSchema { name: "command", value_type: ValueType::Text, description: "PowerShell command with full output transcript", is_uid_component: true },
        FieldSchema { name: "username", value_type: ValueType::Text, description: "User context for the transcript session", is_uid_component: false },
    ],
    retention: Some("Persistent; accumulate indefinitely unless cleared by policy"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["psreadline_history", "evtx_powershell"],
    sources: &[
        "https://attack.mitre.org/techniques/T1059/001/",
        "https://www.sans.org/blog/powershell-forensics-auditing/",
        "https://devblogs.microsoft.com/powershell/powershell-the-blue-team/",
    ],
};

// ── Remote Access Tools ───────────────────────────────────────────────────────

pub(crate) static TEAMVIEWER_CONNECTION_LOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "teamviewer_connection_log",
    name: "TeamViewer Incoming Connections Log",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Program Files*\TeamViewer\connections_incoming.txt"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Plain-text log of all inbound TeamViewer sessions with partner ID, display name, connection timestamps (start and end), and connection type. Critical for establishing timeline of remote access. Partner IDs can be traced back to accounts via TeamViewer's support portal.",
    mitre_techniques: &["T1219"],
    fields: &[
        FieldSchema { name: "partner_id", value_type: ValueType::Text, description: "TeamViewer ID of the remote party", is_uid_component: true },
        FieldSchema { name: "start_time", value_type: ValueType::Timestamp, description: "Session start timestamp", is_uid_component: false },
        FieldSchema { name: "end_time", value_type: ValueType::Timestamp, description: "Session end timestamp", is_uid_component: false },
    ],
    retention: Some("Persists; appended with each connection"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["teamviewer_app_log"],
    sources: &[
        "https://attack.mitre.org/techniques/T1219/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/TeamViewer.tkape",
        "https://www.kroll.com/en/insights/publications/cyber/teamviewer-forensics",
        "https://dfir.blog/teamviewer-forensics/",
    ],
};

pub(crate) static TEAMVIEWER_APP_LOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "teamviewer_app_log",
    name: "TeamViewer Application Log",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\TeamViewer\TeamViewer*_Logfile.log"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Verbose TeamViewer application log with session details, negotiated encryption, file transfers, and connection events. Complements connections_incoming.txt with richer diagnostic data. File transfer events and remote print spooling events are logged here.",
    mitre_techniques: &["T1219"],
    fields: &[
        FieldSchema { name: "event", value_type: ValueType::Text, description: "TeamViewer log event description", is_uid_component: true },
    ],
    retention: Some("Rotated; multiple dated log files may exist"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["teamviewer_connection_log"],
    sources: &[
        "https://attack.mitre.org/techniques/T1219/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/TeamViewer.tkape",
        "https://dfir.blog/teamviewer-forensics/",
    ],
};

pub(crate) static ANYDESK_TRACE_USER: ArtifactDescriptor = ArtifactDescriptor {
    id: "anydesk_trace_user",
    name: "AnyDesk Trace Log (User)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\AnyDesk\ad.trace"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Primary AnyDesk log file for per-user installation. Contains session events: incoming/outgoing connection requests, authentication attempts, session open/close with timestamps, remote host alias or ID, and file transfer events. AnyDesk is heavily abused in BEC/ransomware campaigns for persistent remote access.",
    mitre_techniques: &["T1219"],
    fields: &[
        FieldSchema { name: "anydesk_id", value_type: ValueType::Text, description: "Remote AnyDesk client ID", is_uid_component: true },
        FieldSchema { name: "event_time", value_type: ValueType::Timestamp, description: "Log event timestamp", is_uid_component: false },
    ],
    retention: Some("Rotated at size limit; ad.trace.old retains previous session"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["anydesk_trace_system", "anydesk_connection_trace"],
    sources: &[
        "https://attack.mitre.org/techniques/T1219/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/AnyDesk.tkape",
        "https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-025a",
        "https://dfir.blog/anydesk-forensics/",
    ],
};

pub(crate) static ANYDESK_TRACE_SYSTEM: ArtifactDescriptor = ArtifactDescriptor {
    id: "anydesk_trace_system",
    name: "AnyDesk Service Trace Log (System)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\ProgramData\AnyDesk\ad_svc.trace"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "AnyDesk service-mode (unattended access) log file. Generated when AnyDesk is installed as a Windows service for persistent access without user login. Most relevant for detecting unattended persistent backdoor installations. Records service start/stop, incoming sessions, and policy enforcement.",
    mitre_techniques: &["T1219"],
    fields: &[
        FieldSchema { name: "anydesk_id", value_type: ValueType::Text, description: "Remote AnyDesk client ID", is_uid_component: true },
        FieldSchema { name: "event_time", value_type: ValueType::Timestamp, description: "Log event timestamp", is_uid_component: false },
    ],
    retention: Some("Rotated at size limit"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["anydesk_trace_user", "anydesk_connection_trace"],
    sources: &[
        "https://attack.mitre.org/techniques/T1219/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/AnyDesk.tkape",
        "https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-025a",
        "https://dfir.blog/anydesk-forensics/",
    ],
};

pub(crate) static ANYDESK_CONNECTION_TRACE: ArtifactDescriptor = ArtifactDescriptor {
    id: "anydesk_connection_trace",
    name: "AnyDesk Connection Trace",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\AnyDesk\connection_trace.txt"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Structured log of inbound and outbound AnyDesk connections with remote ID, session type, timestamps, and duration. More terse than ad.trace but specifically designed for connection auditing. Contains outbound connections that prove the local user connected to remote hosts.",
    mitre_techniques: &["T1219"],
    fields: &[
        FieldSchema { name: "remote_id", value_type: ValueType::Text, description: "Remote AnyDesk ID or alias", is_uid_component: true },
        FieldSchema { name: "session_start", value_type: ValueType::Timestamp, description: "Connection start time", is_uid_component: false },
        FieldSchema { name: "direction", value_type: ValueType::Text, description: "in/out — inbound or outbound connection", is_uid_component: false },
    ],
    retention: Some("Appended; grows until manually cleared"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["anydesk_trace_user", "anydesk_file_transfer_log"],
    sources: &[
        "https://attack.mitre.org/techniques/T1219/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/AnyDesk.tkape",
        "https://dfir.blog/anydesk-forensics/",
    ],
};

pub(crate) static ANYDESK_FILE_TRANSFER_LOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "anydesk_file_transfer_log",
    name: "AnyDesk File Transfer Log",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\AnyDesk\file_transfer_trace.txt"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Log of files transferred via AnyDesk file manager per session — filename, size, direction (sent/received), and timestamp. Direct evidence of data exfiltration (files sent to remote operator) or tooling delivery (files received from attacker). Persists even after remote session cleanup attempts.",
    mitre_techniques: &["T1219"],
    fields: &[
        FieldSchema { name: "filename", value_type: ValueType::Text, description: "Name of file transferred", is_uid_component: true },
        FieldSchema { name: "direction", value_type: ValueType::Text, description: "sent or received", is_uid_component: false },
        FieldSchema { name: "transfer_time", value_type: ValueType::Timestamp, description: "Transfer timestamp", is_uid_component: false },
    ],
    retention: Some("Appended; grows until manually cleared"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["anydesk_connection_trace", "anydesk_trace_user"],
    sources: &[
        "https://attack.mitre.org/techniques/T1219/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/AnyDesk.tkape",
        "https://dfir.blog/anydesk-forensics/",
    ],
};

pub(crate) static SCREENCONNECT_SESSION_DB: ArtifactDescriptor = ArtifactDescriptor {
    id: "screenconnect_session_db",
    name: "ScreenConnect / ConnectWise Control Session Database",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Program Files*\ScreenConnect\App_Data\Session.db"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "SQLite database for ConnectWise Control (formerly ScreenConnect) self-hosted server containing all session records with connecting client IP, session name, connection start/end timestamps, and operator identity. Critical when attackers deploy their own self-hosted ScreenConnect server on compromised infrastructure.",
    mitre_techniques: &["T1219"],
    fields: &[
        FieldSchema { name: "session_name", value_type: ValueType::Text, description: "Session display name", is_uid_component: true },
        FieldSchema { name: "session_start", value_type: ValueType::Timestamp, description: "Session creation timestamp", is_uid_component: false },
        FieldSchema { name: "participant_ip", value_type: ValueType::Text, description: "Connecting client IP address", is_uid_component: false },
    ],
    retention: Some("Persistent; retained until database manually cleared or rotated"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["teamviewer_connection_log", "anydesk_trace_system"],
    sources: &[
        "https://attack.mitre.org/techniques/T1219/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/ScreenConnect.tkape",
        "https://www.cisa.gov/news-events/cybersecurity-advisories/aa24-241a",
    ],
};

pub(crate) static RUSTDESK_LOGS: ArtifactDescriptor = ArtifactDescriptor {
    id: "rustdesk_logs",
    name: "RustDesk Logs Directory",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\RustDesk"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Log and configuration directory for RustDesk open-source remote desktop tool. Increasingly used by threat actors as an alternative to AnyDesk (same protocol, self-hostable relay). Contains RustDesk.log with connection events, config.toml with relay server settings (attacker-controlled relay is a key IoC), and id/password files.",
    mitre_techniques: &["T1219"],
    fields: &[
        FieldSchema { name: "peer_id", value_type: ValueType::Text, description: "Remote RustDesk peer ID", is_uid_component: true },
    ],
    retention: Some("Log rotated at size limit; config files persistent"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["anydesk_trace_user", "teamviewer_connection_log"],
    sources: &[
        "https://attack.mitre.org/techniques/T1219/",
        "https://thedfirreport.com/2024/08/12/threat-actors-toolkit-leveraging-sliver-poshc2-and-batch-scripts/",
        "https://github.com/rustdesk/rustdesk",
    ],
};

// ── Cloud Storage ─────────────────────────────────────────────────────────────

pub(crate) static DROPBOX_INSTANCE_DB: ArtifactDescriptor = ArtifactDescriptor {
    id: "dropbox_instance_db",
    name: "Dropbox Instance Database Directory",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Local\Dropbox\instance*"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Core Dropbox SQLite databases including sync.db (file sync history with server hashes), config.db (account configuration), and filecache.db (local file metadata). Contains complete listing of all files ever synced to Dropbox including deleted files. Critical for data exfiltration investigations.",
    mitre_techniques: &["T1567.002"],
    fields: &[
        FieldSchema { name: "server_path", value_type: ValueType::Text, description: "Dropbox server-side file path", is_uid_component: true },
        FieldSchema { name: "modified_time", value_type: ValueType::Timestamp, description: "File last modification timestamp", is_uid_component: false },
    ],
    retention: Some("Persists until Dropbox uninstalled or database pruned"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["onedrive_metadata", "google_drive_fs_metadata"],
    sources: &[
        "https://attack.mitre.org/techniques/T1567/002/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/Dropbox.tkape",
        "https://www.sans.org/blog/cloud-storage-forensics-dropbox-google-drive-and-onedrive/",
        "https://dfir.blog/dropbox-forensics/",
    ],
};

pub(crate) static ONEDRIVE_METADATA: ArtifactDescriptor = ArtifactDescriptor {
    id: "onedrive_metadata",
    name: "OneDrive Sync Client Metadata",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Local\Microsoft\OneDrive"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "OneDrive sync client databases and logs. Key files: SyncEngineDatabase.db (file sync history and metadata for all OneDrive files including cloud-only placeholders), *.odl log files (diagnostic activity). Exposes files uploaded to OneDrive even when not stored locally — including exfiltrated documents.",
    mitre_techniques: &["T1567.002"],
    fields: &[
        FieldSchema { name: "local_path", value_type: ValueType::Text, description: "Local file path", is_uid_component: true },
        FieldSchema { name: "sha1_hash", value_type: ValueType::Text, description: "File SHA-1 hash for cloud deduplication", is_uid_component: false },
    ],
    retention: Some("Persists; ODL log files rotate"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["dropbox_instance_db", "google_drive_fs_metadata"],
    sources: &[
        "https://attack.mitre.org/techniques/T1567/002/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/OneDrive.tkape",
        "https://www.sans.org/blog/cloud-storage-forensics-dropbox-google-drive-and-onedrive/",
        "https://github.com/barnettjw/ODL-Parser",
    ],
};

pub(crate) static GOOGLE_DRIVE_FS_METADATA: ArtifactDescriptor = ArtifactDescriptor {
    id: "google_drive_fs_metadata",
    name: "Google Drive for Desktop Metadata",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Local\Google\DriveFS"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Google Drive for Desktop (formerly Backup and Sync) metadata database directory. Contains metadata.db with SQLite records of all files in the user's Drive including cloud-only files, their local sync status, content hash, and modification timestamps. Exposes exfiltrated data paths even when files are not cached locally.",
    mitre_techniques: &["T1567.002"],
    fields: &[
        FieldSchema { name: "stable_id", value_type: ValueType::Text, description: "Google Drive stable file identifier", is_uid_component: true },
        FieldSchema { name: "title", value_type: ValueType::Text, description: "File or folder name", is_uid_component: false },
        FieldSchema { name: "modified_date", value_type: ValueType::Timestamp, description: "Last modification timestamp", is_uid_component: false },
    ],
    retention: Some("Persists until Drive for Desktop uninstalled"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["dropbox_instance_db", "onedrive_metadata"],
    sources: &[
        "https://attack.mitre.org/techniques/T1567/002/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/GoogleDrive.tkape",
        "https://www.sans.org/blog/cloud-storage-forensics-dropbox-google-drive-and-onedrive/",
    ],
};

pub(crate) static MEGASYNC_DATA: ArtifactDescriptor = ArtifactDescriptor {
    id: "megasync_data",
    name: "MEGAsync Cloud Storage Data",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Local\Mega Limited\MEGAsync"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "MEGA cloud storage client data directory. Contains sync configuration and logs. MEGA is frequently used by ransomware groups (BlackCat/ALPHV, LockBit) for data exfiltration prior to encryption due to its end-to-end encryption making detection harder. MEGAsync.log records file sync events.",
    mitre_techniques: &["T1567.002"],
    fields: &[
        FieldSchema { name: "sync_path", value_type: ValueType::Text, description: "Local path being synced to MEGA", is_uid_component: true },
    ],
    retention: Some("Log rotated at size; configuration persists"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["dropbox_instance_db", "onedrive_metadata"],
    sources: &[
        "https://attack.mitre.org/techniques/T1567/002/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/MEGAsync.tkape",
        "https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-165a",
    ],
};

// ── Communications ────────────────────────────────────────────────────────────

pub(crate) static TEAMS_INDEXED_DB: ArtifactDescriptor = ArtifactDescriptor {
    id: "teams_indexed_db",
    name: "Microsoft Teams IndexedDB (Chat History)",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\Microsoft\Teams\IndexedDB\https_teams.microsoft.com_0.indexeddb.leveldb"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "LevelDB database of Microsoft Teams desktop client containing cached chat messages, channel history, call logs, and file share metadata. Reconstructable with LevelDB parsers. Critical for insider threat investigations and social engineering chain reconstruction.",
    mitre_techniques: &[],
    fields: &[
        FieldSchema { name: "conversation_id", value_type: ValueType::Text, description: "Teams conversation identifier", is_uid_component: true },
        FieldSchema { name: "message_content", value_type: ValueType::Text, description: "Message text content", is_uid_component: false },
    ],
    retention: Some("Cached locally; synced with Teams service; grows until cleared"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["slack_indexed_db", "signal_database"],
    sources: &[
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/MicrosoftTeams.tkape",
        "https://www.sans.org/blog/microsoft-teams-forensics/",
        "https://bsodtutorials.wordpress.com/2021/05/24/microsoft-teams-forensics/",
    ],
};

pub(crate) static SLACK_INDEXED_DB: ArtifactDescriptor = ArtifactDescriptor {
    id: "slack_indexed_db",
    name: "Slack IndexedDB (Message Cache)",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\Slack\IndexedDB"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "LevelDB cache of Slack desktop client containing channel messages, DMs, and workspace metadata. Provides investigative intelligence on attacker-impersonated employees in phishing chains and insider threat communication. File share metadata reveals exfiltrated file names.",
    mitre_techniques: &[],
    fields: &[
        FieldSchema { name: "channel_id", value_type: ValueType::Text, description: "Slack channel identifier", is_uid_component: true },
        FieldSchema { name: "message_text", value_type: ValueType::Text, description: "Message content", is_uid_component: false },
    ],
    retention: Some("Locally cached; grows until Slack cache cleared"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["teams_indexed_db", "discord_local_storage"],
    sources: &[
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/Slack.tkape",
        "https://www.sans.org/blog/slack-forensics-investigations-in-the-enterprise/",
    ],
};

pub(crate) static DISCORD_LOCAL_STORAGE: ArtifactDescriptor = ArtifactDescriptor {
    id: "discord_local_storage",
    name: "Discord Local Storage (LevelDB)",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\discord\Local Storage\leveldb"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "LevelDB local storage for Discord desktop client. May contain cached Discord authentication tokens recoverable via memory or disk parsing — a primary target for info-stealers. Discord is used as a C2 channel and exfiltration destination by multiple threat actors. Token theft enables account takeover.",
    mitre_techniques: &["T1539"],
    fields: &[
        FieldSchema { name: "token", value_type: ValueType::Text, description: "Discord authentication token (if recoverable)", is_uid_component: true },
    ],
    retention: Some("Persists until Discord uninstalled or localStorage cleared"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["slack_indexed_db", "chrome_login_data"],
    sources: &[
        "https://attack.mitre.org/techniques/T1539/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/Discord.tkape",
        "https://www.bleepingcomputer.com/news/security/discord-token-stealers-on-the-rise-heres-what-you-can-do/",
    ],
};

pub(crate) static SIGNAL_DATABASE: ArtifactDescriptor = ArtifactDescriptor {
    id: "signal_database",
    name: "Signal Desktop Message Database",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\Signal\sql\db.sqlite"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "SQLCipher-encrypted SQLite database containing all Signal Desktop messages, contacts, and call history. Encrypted at rest with a key stored in config.json. When decryption key is recovered, provides full message plaintext. Relevant to investigations involving encrypted communication in drug trafficking, espionage, and organized crime.",
    mitre_techniques: &[],
    fields: &[
        FieldSchema { name: "message_body", value_type: ValueType::Text, description: "Decrypted message content (when key recovered)", is_uid_component: true },
        FieldSchema { name: "sent_at", value_type: ValueType::Timestamp, description: "Message sent timestamp", is_uid_component: false },
    ],
    retention: Some("Persists until explicitly deleted by user"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["signal_config_json", "teams_indexed_db"],
    sources: &[
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/Signal.tkape",
        "https://www.cise.ufl.edu/~traynor/papers/signal-forensics.pdf",
        "https://www.magnetforensics.com/blog/forensic-analysis-of-signal-desktop/",
    ],
};

pub(crate) static SIGNAL_CONFIG_JSON: ArtifactDescriptor = ArtifactDescriptor {
    id: "signal_config_json",
    name: "Signal Desktop config.json (DB Encryption Key)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Roaming\Signal\config.json"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "JSON configuration file containing the plaintext SQLCipher encryption key for Signal's db.sqlite. The key field contains the hex-encoded 256-bit AES key required to decrypt all Signal messages. This is a critical vulnerability in Signal Desktop's security model on Windows — any process with user-level access can decrypt all messages.",
    mitre_techniques: &["T1552.001"],
    fields: &[
        FieldSchema { name: "key", value_type: ValueType::Text, description: "Hex-encoded AES-256 SQLCipher key for db.sqlite", is_uid_component: true },
    ],
    retention: Some("Persistent; regenerated only on fresh installation"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["signal_database"],
    sources: &[
        "https://attack.mitre.org/techniques/T1552/001/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Apps/Signal.tkape",
        "https://www.magnetforensics.com/blog/forensic-analysis-of-signal-desktop/",
        "https://www.bleepingcomputer.com/news/security/signal-desktop-app-stores-messages-in-plaintext-unencrypted-folder/",
    ],
};

// ── Windows Forensic Files ────────────────────────────────────────────────────

pub(crate) static WINDOWS_SEARCH_EDB: ArtifactDescriptor = ArtifactDescriptor {
    id: "windows_search_edb",
    name: "Windows Search Index Database (Windows.edb)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\ProgramData\Microsoft\Search\Data\Applications\Windows\Windows.edb"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Extensible Storage Engine (ESE) database containing Windows Search index. Stores content extracted from indexed files including email bodies, document text, and metadata. Contains evidence of file content even after files have been deleted, and indexes network shares visited by the user.",
    mitre_techniques: &["T1083"],
    fields: &[
        FieldSchema { name: "file_path", value_type: ValueType::Text, description: "Indexed file path", is_uid_component: true },
        FieldSchema { name: "last_modified", value_type: ValueType::Timestamp, description: "File last modification time as indexed", is_uid_component: false },
    ],
    retention: Some("Rebuilt on corruption; grows until disk pressure forces cleanup"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["mft_file", "ntuser_dat_file"],
    sources: &[
        "https://attack.mitre.org/techniques/T1083/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/WindowsIndexSearch.tkape",
        "https://www.foxtonforensics.com/blog/post/analysing-the-windows-search-database",
    ],
};

pub(crate) static EVENT_TRANSCRIPT_DB: ArtifactDescriptor = ArtifactDescriptor {
    id: "event_transcript_db",
    name: "Windows Telemetry EventTranscript.db",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\ProgramData\Microsoft\Diagnosis\EventTranscript\EventTranscript.db"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "SQLite database collecting Windows Diagnostic Data (telemetry) events including application launches, census data, and diagnostic payloads in JSON format. The events table contains timestamped JSON blobs recording application execution and system activity — functions as an alternative execution timeline independent of prefetch and event logs.",
    mitre_techniques: &[],
    fields: &[
        FieldSchema { name: "provider_group_guid", value_type: ValueType::Text, description: "Telemetry provider GUID", is_uid_component: true },
        FieldSchema { name: "logging_binary_name", value_type: ValueType::Text, description: "Application that generated the event", is_uid_component: false },
        FieldSchema { name: "event_keywords", value_type: ValueType::Text, description: "Event classification keywords", is_uid_component: false },
    ],
    retention: Some("Managed by DiagTrack; rotated automatically"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["srum_db", "windows_timeline"],
    sources: &[
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/WindowsDiagnosticData.tkape",
        "https://www.geoffchappell.com/studies/windows/km/ntoskrnl/api/etw/logapi/query.htm",
        "https://www.sans.org/blog/digital-forensics-dfir/",
    ],
};

pub(crate) static CERTUTIL_CACHE: ArtifactDescriptor = ArtifactDescriptor {
    id: "certutil_cache",
    name: "CertUtil URL Cache (certutil -urlcache)",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Windows\System32\config\systemprofile\AppData\LocalLow\Microsoft\CryptnetUrlCache\Content"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Cache directory populated by certutil.exe when used to download files via HTTP/HTTPS (LOLBin technique). Files downloaded with `certutil -urlcache -split -f <url>` are stored here. Evidence of file download persists even after the downloaded file is deleted. File names are hashed but creation timestamps align with download time.",
    mitre_techniques: &["T1105"],
    fields: &[
        FieldSchema { name: "cached_file", value_type: ValueType::Text, description: "Hash-named cached file (content is the downloaded data)", is_uid_component: true },
        FieldSchema { name: "download_time", value_type: ValueType::Timestamp, description: "File creation time = download time", is_uid_component: false },
    ],
    retention: Some("Persists until CryptNet cache is flushed"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["evtx_powershell", "psreadline_history"],
    sources: &[
        "https://attack.mitre.org/techniques/T1105/",
        "https://lolbas-project.github.io/lolbas/Binaries/Certutil/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/CertUtil.tkape",
        "https://www.sans.org/blog/certutil-is-a-lolbin/",
    ],
};

pub(crate) static SDB_CUSTOM_FILES: ArtifactDescriptor = ArtifactDescriptor {
    id: "sdb_custom_files",
    name: "Custom AppCompat Shim Database Files",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Windows\apppatch\Custom\"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Directory containing custom Application Compatibility shim databases (.sdb files). Attackers install custom SDB files as a persistence mechanism (T1546.011 — Application Shimming). Shims can redirect API calls, inject DLLs, or modify application behavior without modifying the target binary. Legitimately rare; any .sdb file here in an incident warrants investigation.",
    mitre_techniques: &["T1546.011"],
    fields: &[
        FieldSchema { name: "sdb_file", value_type: ValueType::Text, description: "Custom shim database filename", is_uid_component: true },
    ],
    retention: Some("Persistent until explicitly uninstalled"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["appshim_db"],
    sources: &[
        "https://attack.mitre.org/techniques/T1546/011/",
        "https://www.fireeye.com/blog/threat-research/2017/05/fin7-shim-databases-persistence.html",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/AppCompatSDBFiles.tkape",
        "https://www.hexacorn.com/blog/2015/07/17/beyond-good-ol-run-key-part-38/",
    ],
};

pub(crate) static WER_REPORTS: ArtifactDescriptor = ArtifactDescriptor {
    id: "wer_reports",
    name: "Windows Error Reporting Queue",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\ProgramData\Microsoft\Windows\WER\ReportQueue\"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Queued Windows Error Reporting crash reports. Each report directory contains a Report.wer metadata file with the crashing application name, version, crash timestamp, and module name. WER reports prove execution of the crashing process even after binary deletion — injected processes crash frequently, generating WER artifacts.",
    mitre_techniques: &["T1055"],
    fields: &[
        FieldSchema { name: "app_name", value_type: ValueType::Text, description: "Name of the crashing application", is_uid_component: true },
        FieldSchema { name: "crash_time", value_type: ValueType::Timestamp, description: "Crash event timestamp", is_uid_component: false },
        FieldSchema { name: "module_name", value_type: ValueType::Text, description: "Faulting module name", is_uid_component: false },
    ],
    retention: Some("Queued reports purged after submission; max ~50 reports"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["evtx_system", "prefetch_dir"],
    sources: &[
        "https://attack.mitre.org/techniques/T1055/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/WindowsErrorReporting.tkape",
        "https://www.sans.org/blog/windows-error-reporting-forensics/",
    ],
};

pub(crate) static IIS_W3SVC_LOGS: ArtifactDescriptor = ArtifactDescriptor {
    id: "iis_w3svc_logs",
    name: "IIS W3C HTTP Access Logs",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Windows\System32\LogFiles\W3SVC*"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "IIS web server W3C Extended Log Format access logs. Each log line records date, time, client IP, server IP, HTTP method, URI stem, URI query, HTTP status, bytes sent/received, time-taken, and user-agent. Primary source for web exploitation evidence including webshell activity, SQLi attempts, and LFI/path traversal.",
    mitre_techniques: &["T1190"],
    fields: &[
        FieldSchema { name: "client_ip", value_type: ValueType::Text, description: "Client IP address", is_uid_component: true },
        FieldSchema { name: "uri_stem", value_type: ValueType::Text, description: "Requested URI path", is_uid_component: false },
        FieldSchema { name: "uri_query", value_type: ValueType::Text, description: "URI query string (exploit payload often here)", is_uid_component: false },
        FieldSchema { name: "sc_status", value_type: ValueType::UnsignedInt, description: "HTTP response status code", is_uid_component: false },
    ],
    retention: Some("Rotated daily by default; retention per IIS configuration"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["iis_config_applicationhost", "evtx_system"],
    sources: &[
        "https://attack.mitre.org/techniques/T1190/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Logs/IISLogFiles.tkape",
        "https://www.sans.org/blog/iis-log-forensics/",
        "https://docs.microsoft.com/en-us/iis/manage/provisioning-and-managing-iis/configure-logging-in-iis",
    ],
};

pub(crate) static IIS_CONFIG_APPLICATIONHOST: ArtifactDescriptor = ArtifactDescriptor {
    id: "iis_config_applicationhost",
    name: "IIS applicationHost.config",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Windows\System32\inetsrv\config\applicationHost.config"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Master IIS server configuration file defining all web sites, application pools, virtual directories, authentication, and handler mappings. Attacker-added script handlers (e.g., .aspx mapped to a malicious ISAPI DLL) and ISAPI extension registrations for native webshells appear here. Reveals full web root paths for evidence collection.",
    mitre_techniques: &["T1505.004"],
    fields: &[
        FieldSchema { name: "site_name", value_type: ValueType::Text, description: "IIS web site name", is_uid_component: true },
        FieldSchema { name: "physical_path", value_type: ValueType::Text, description: "Web root physical path", is_uid_component: false },
    ],
    retention: Some("Persistent; modified by IIS Manager or direct edit"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["iis_w3svc_logs"],
    sources: &[
        "https://attack.mitre.org/techniques/T1505/004/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Logs/IISLogFiles.tkape",
        "https://www.sans.org/blog/iis-log-forensics/",
    ],
};

pub(crate) static DNS_DEBUG_LOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "dns_debug_log",
    name: "DNS Server Debug Log",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Windows\System32\dns\dns.log"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Windows DNS Server verbose debug log recording all query requests with client IP, query name, query type, and response. Enables reconstruction of DNS-based C2 (beaconing patterns to suspicious domains), DNS tunneling (unusually long or encoded subdomains), and internal host enumeration. Requires debug logging to be enabled — check if disabled by attackers.",
    mitre_techniques: &["T1071.004"],
    fields: &[
        FieldSchema { name: "client_ip", value_type: ValueType::Text, description: "IP address of the DNS querying host", is_uid_component: true },
        FieldSchema { name: "query_name", value_type: ValueType::Text, description: "Domain name queried", is_uid_component: false },
        FieldSchema { name: "query_type", value_type: ValueType::Text, description: "DNS record type (A, AAAA, TXT, MX, etc.)", is_uid_component: false },
    ],
    retention: Some("Single file; rotated at configured size limit"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["dhcp_server_log", "evtx_system"],
    sources: &[
        "https://attack.mitre.org/techniques/T1071/004/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Logs/DNSServerLog.tkape",
        "https://www.sans.org/blog/dns-logging-in-windows-server/",
        "https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn800669(v=ws.11)",
    ],
};

pub(crate) static DHCP_SERVER_LOG: ArtifactDescriptor = ArtifactDescriptor {
    id: "dhcp_server_log",
    name: "Windows DHCP Server Log",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Windows\System32\dhcp\DhcpSrvLog-*.log"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Windows DHCP Server audit log recording IP address assignments with MAC address, hostname, and timestamp. Critical for correlating IP addresses in other logs (firewall, IIS, DNS) with specific physical devices. Lease event 10=Assign, 11=Renew, 12=Release — timestamps anchor IP-to-host mapping windows.",
    mitre_techniques: &["T1016"],
    fields: &[
        FieldSchema { name: "ip_address", value_type: ValueType::Text, description: "IP address assigned", is_uid_component: true },
        FieldSchema { name: "mac_address", value_type: ValueType::Text, description: "Client MAC address", is_uid_component: false },
        FieldSchema { name: "hostname", value_type: ValueType::Text, description: "Client-reported hostname", is_uid_component: false },
        FieldSchema { name: "event_time", value_type: ValueType::Timestamp, description: "DHCP event timestamp", is_uid_component: false },
    ],
    retention: Some("One file per day; typically 7-day retention"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["dns_debug_log", "evtx_system"],
    sources: &[
        "https://attack.mitre.org/techniques/T1016/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Logs/DHCPServerLog.tkape",
        "https://www.ired.team/offensive-security-experiments/active-directory-kerberos-abuse/active-directory-enumeration-with-ad-module-without-rsat",
    ],
};

pub(crate) static SUM_DB: ArtifactDescriptor = ArtifactDescriptor {
    id: "sum_db",
    name: "User Access Logging (SUM) Database",
    artifact_type: ArtifactType::Directory,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Windows\System32\LogFiles\SUM\"),
    scope: DataScope::System,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Windows Server User Access Logging (UAL) database directory containing Current.mdb and {GUID}.mdb JET ESE databases. Records authenticated access to server roles (IIS, SMB/file sharing, RDS) with source IP, username, and first/last access timestamps. Retains up to 2 years of history. Critical for server compromise investigations — shows what accounts accessed what services and from where.",
    mitre_techniques: &["T1021"],
    fields: &[
        FieldSchema { name: "username", value_type: ValueType::Text, description: "Authenticated username", is_uid_component: true },
        FieldSchema { name: "ip_address", value_type: ValueType::Text, description: "Client IP address", is_uid_component: false },
        FieldSchema { name: "first_seen", value_type: ValueType::Timestamp, description: "First access timestamp for this username/IP pair", is_uid_component: false },
        FieldSchema { name: "last_seen", value_type: ValueType::Timestamp, description: "Last access timestamp", is_uid_component: false },
    ],
    retention: Some("Up to 2 years; rolled annually into yearly GUID-named DB"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["evtx_security", "dns_debug_log", "dhcp_server_log"],
    sources: &[
        "https://attack.mitre.org/techniques/T1021/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/UserAccessLogging.tkape",
        "https://www.sans.org/blog/windows-user-access-logging-sum/",
        "https://advisory.kpmg.us/blog/2021/digital-forensics-incident-response.html",
    ],
};

pub(crate) static COPILOT_RECALL_UKG: ArtifactDescriptor = ArtifactDescriptor {
    id: "copilot_recall_ukg",
    name: "Windows Recall Screenshot Index (ukg.db)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Local\CoreAIPlatform.00\UKP\*\ukg.db"),
    scope: DataScope::User,
    os_scope: OsScope::Win11Plus,
    decoder: Decoder::Identity,
    meaning: "Windows Copilot+ Recall feature screenshot index database. Contains OCR-extracted text from periodic screenshots of all user activity, searchable by content. Provides near-complete reconstruction of user desktop activity including credential entry, browsing, and document editing. Protected by VBS/PPLA on compliant hardware, but accessible forensically from acquired images.",
    mitre_techniques: &["T1113"],
    fields: &[
        FieldSchema { name: "ocr_text", value_type: ValueType::Text, description: "OCR-extracted text from screenshot", is_uid_component: true },
        FieldSchema { name: "screenshot_time", value_type: ValueType::Timestamp, description: "Timestamp of the captured screenshot", is_uid_component: false },
        FieldSchema { name: "window_title", value_type: ValueType::Text, description: "Active window title at time of screenshot", is_uid_component: false },
    ],
    retention: Some("Rolling 90-day window by default; configurable"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["windows_timeline", "srum_db"],
    sources: &[
        "https://attack.mitre.org/techniques/T1113/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/WindowsRecall.tkape",
        "https://doublepulsar.com/recall-stealing-everything-youve-ever-typed-or-viewed-on-your-own-windows-pc-is-now-possible-da3e12e9465e",
        "https://www.bleepingcomputer.com/news/microsoft/microsoft-recall-now-available-to-all-windows-insiders/",
    ],
};

pub(crate) static NTUSER_DAT_FILE: ArtifactDescriptor = ArtifactDescriptor {
    id: "ntuser_dat_file",
    name: "NTUSER.DAT (Per-User Registry Hive)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\NTUSER.DAT"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "Per-user registry hive containing all HKEY_CURRENT_USER data for the user profile. Source for all HKCU-scoped artifacts: Run keys, UserAssist, TypedURLs, MRU lists, RecentDocs, shellbags, proxy settings, and thousands more. A single NTUSER.DAT file provides the complete user activity registry picture for offline forensics.",
    mitre_techniques: &["T1012"],
    fields: &[
        FieldSchema { name: "username", value_type: ValueType::Text, description: "Username inferred from profile path", is_uid_component: true },
    ],
    retention: Some("Exists for lifetime of user profile"),
    triage_priority: TriagePriority::Critical,
    related_artifacts: &["usrclass_dat_file", "shellbags_user", "run_key_hkcu_run"],
    sources: &[
        "https://attack.mitre.org/techniques/T1012/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/RegistryHivesUser.tkape",
        "https://13cubed.com/downloads/Windows_Forensic_Analysis_Poster.pdf",
        "https://www.sans.org/blog/digital-forensics-artifacts-in-windows-registry/",
    ],
};

pub(crate) static USRCLASS_DAT_FILE: ArtifactDescriptor = ArtifactDescriptor {
    id: "usrclass_dat_file",
    name: "UsrClass.dat (User Classes Registry Hive)",
    artifact_type: ArtifactType::File,
    hive: None,
    key_path: "",
    value_name: None,
    file_path: Some(r"C:\Users\*\AppData\Local\Microsoft\Windows\UsrClass.dat"),
    scope: DataScope::User,
    os_scope: OsScope::Win10Plus,
    decoder: Decoder::Identity,
    meaning: "User-specific COM class registration and shellbags hive (HKCU\\Software\\Classes). Primary source for shellbag artifacts covering virtual folders (Desktop, Libraries, Network, ZIP contents) that NTUSER.DAT shellbags miss. Shellbags persist folder access evidence long after files are deleted — critical for proving directory traversal.",
    mitre_techniques: &["T1083"],
    fields: &[
        FieldSchema { name: "username", value_type: ValueType::Text, description: "Username inferred from profile path", is_uid_component: true },
    ],
    retention: Some("Exists for lifetime of user profile"),
    triage_priority: TriagePriority::High,
    related_artifacts: &["ntuser_dat_file", "shellbags_user"],
    sources: &[
        "https://attack.mitre.org/techniques/T1083/",
        "https://github.com/EricZimmerman/KapeFiles/blob/master/Targets/Windows/RegistryHivesUser.tkape",
        "https://www.sans.org/blog/windows-shellbag-forensics-in-depth/",
    ],
};
