//! Combined artifact profile — evidence strength + volatility in one place.
//!
//! [`ARTIFACT_PROFILES`] is the single authoritative table that merges
//! [`crate::evidence::EVIDENCE_TABLE`] and [`crate::volatility::VOLATILITY_TABLE`].
//! Adding a new artifact requires only one edit here.
//!
//! Use [`profile_for`] for point-lookups, or iterate [`ARTIFACT_PROFILES`] for
//! bulk operations.

use crate::evidence::EvidenceStrength;
use crate::volatility::VolatilityClass;

/// Combined profile: evidence weight + acquisition urgency for one artifact.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[non_exhaustive]
#[cfg_attr(feature = "serde", derive(serde::Serialize))]
pub struct ArtifactProfile {
    /// Catalog artifact ID (same key used in [`crate::catalog::CATALOG`]).
    pub id: &'static str,
    /// How strongly this artifact proves a fact in isolation.
    pub evidence_strength: EvidenceStrength,
    /// Known caveats, edge cases, or false-positive scenarios.
    pub evidence_caveats: &'static [&'static str],
    /// How quickly this artifact is overwritten or lost (RFC 3227 class).
    pub volatility: VolatilityClass,
    /// One-line rationale for the volatility classification.
    pub volatility_rationale: &'static str,
}

/// Merged profile table (236 entries, one per catalog artifact).
///
/// Combines all entries from `EVIDENCE_TABLE` and `VOLATILITY_TABLE`.
/// For artifacts that appeared in only one of the legacy tables, the missing
/// dimension is filled with a conservative default.
pub static ARTIFACT_PROFILES: &[ArtifactProfile] = &[
    ArtifactProfile {
        id: "amcache_app_file",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &[
            "Presence proves file was on disk and touched by Windows; not always execution",
            "Can be populated by antivirus scans",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Persists until Windows Update or manual clear",
    },
    ArtifactProfile {
        id: "bam_user",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Granularity is per-day; precise execution time not available"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Rotated by OS on background activity manager flush",
    },
    ArtifactProfile {
        id: "dam_user",
        evidence_strength: EvidenceStrength::Corroborative,
        evidence_caveats: &["Device Activity Monitor; less studied than BAM"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Rotated by OS on desktop activity monitor flush",
    },
    ArtifactProfile {
        id: "prefetch_file",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Prefetch can be disabled via registry; absence does not mean no execution"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Max 1024 entries, FIFO eviction on Win10+",
    },
    ArtifactProfile {
        id: "shimcache",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &[
            "Presence proves file existed on disk, not necessarily executed",
            "Written only on reboot; live system shows stale data",
        ],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "Written to registry only on shutdown; live state is in memory",
    },
    ArtifactProfile {
        id: "userassist_exe",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Counts GUI application launches; CLI-only execution not recorded",
            "ROT13 name encoding can be misread if decoder is missing",
        ],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Updated per user GUI interaction; persists in NTUSER.DAT",
    },
    ArtifactProfile {
        id: "active_setup_hklm",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Registry key presence is definitive persistence evidence; compare sub-key StubPath against known-good baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persists until explicit deletion",
    },
    ArtifactProfile {
        id: "appinit_dlls",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Only effective when SecureBoot is disabled"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry value; persists until explicit deletion",
    },
    ArtifactProfile {
        id: "boot_execute",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Any non-default value is highly suspicious; default is autocheck autochk *"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry value; persists until explicit deletion",
    },
    ArtifactProfile {
        id: "com_hijack_clsid_hkcu",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Some legitimate COM redirection exists; compare with HKLM entries"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key per-user; persists in NTUSER.DAT",
    },
    ArtifactProfile {
        id: "ifeo_debugger",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Legitimate debugger keys exist; focus on non-debugger executables"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persists until explicit deletion",
    },
    ArtifactProfile {
        id: "run_key_hkcu",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Per-user; requires knowing which user profile to examine"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Per-user registry key; persists in NTUSER.DAT",
    },
    ArtifactProfile {
        id: "run_key_hklm",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Legitimate software also uses Run keys; context required"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "System registry key; persists until explicit deletion",
    },
    ArtifactProfile {
        id: "run_key_hklm_once",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Single-run key deleted after execution; absence may indicate prior execution; correlate with execution artifacts"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Deleted by OS after single execution",
    },
    ArtifactProfile {
        id: "scheduled_tasks_dir",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Task XML may be deleted after execution; check event log 4698/4702"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "XML files in tasks directory; persist until task deleted",
    },
    ArtifactProfile {
        id: "services_imagepath",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Many legitimate services present; focus on unsigned/unusual paths"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key under SYSTEM; persists until service removed",
    },
    ArtifactProfile {
        id: "winlogon_shell",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Default value is 'explorer.exe'; any deviation is highly suspicious"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry value; persists until explicit deletion",
    },
    ArtifactProfile {
        id: "chrome_login_data",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Credentials encrypted with DPAPI; require user masterkey to decrypt",
            "May contain stale or user-deleted passwords",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SQLite DB; credentials persist until deleted from browser",
    },
    ArtifactProfile {
        id: "dcc2_cache",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Only proves domain user logged in; not current password"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Rotated; last 10 cached credentials by default",
    },
    ArtifactProfile {
        id: "dpapi_cred_user",
        evidence_strength: EvidenceStrength::Corroborative,
        evidence_caveats: &["Encrypted credential blobs; useful with DPAPI master key decryption"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Encrypted credential blobs; persist until explicit deletion",
    },
    ArtifactProfile {
        id: "dpapi_masterkey_user",
        evidence_strength: EvidenceStrength::Corroborative,
        evidence_caveats: &["Presence expected for every user; useful for decrypting other artifacts"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Master keys persist; old keys backed up in AD",
    },
    ArtifactProfile {
        id: "dpapi_system_masterkey",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Required to decrypt SYSTEM-scope DPAPI blobs; requires SYSTEM privilege",
            "Loss of this key means DPAPI-protected data is unrecoverable",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "System DPAPI master key; persists in SYSTEM hive",
    },
    ArtifactProfile {
        id: "firefox_logins",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Encrypted with Firefox key4.db; requires key extraction for plaintext",
            "Primary password (master password) prevents access if set",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "JSON file; credentials persist until deleted from browser",
    },
    ArtifactProfile {
        id: "lsa_secrets",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Requires SYSTEM privileges to read; encrypted at rest"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "System hive registry; persists until credential removed",
    },
    ArtifactProfile {
        id: "ntds_dit",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["All domain hashes present; requires parsing with secretsdump or ntdsutil"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "AD database; persists until account deleted",
    },
    ArtifactProfile {
        id: "sam_users",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Contains local account NTLM hashes; requires SYSTEM privilege to read",
            "Must be used with SYSTEM hive to decrypt",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SAM registry hive; persists until account deleted",
    },
    ArtifactProfile {
        id: "jump_list_auto",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Application-specific; some apps don't integrate with jump lists"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Updated on file access; max entries per app",
    },
    ArtifactProfile {
        id: "jump_list_custom",
        evidence_strength: EvidenceStrength::Corroborative,
        evidence_caveats: &["Pinned items reflect user intent; can be manually set without file access"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Pinned by user; persists until app unpins",
    },
    ArtifactProfile {
        id: "lnk_files",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Can be spoofed; verify with corroborating artifacts"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Created on file open; max ~150 recent items",
    },
    ArtifactProfile {
        id: "mft_file",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &[
            "Timestamps susceptible to timestomping ($STANDARD_INFORMATION vs $FILE_NAME)",
            "$FILE_NAME timestamps harder to tamper; compare both",
        ],
        volatility: VolatilityClass::Residual,
        volatility_rationale: "Metadata persists in unallocated MFT entries after deletion",
    },
    ArtifactProfile {
        id: "mru_recent_docs",
        evidence_strength: EvidenceStrength::Corroborative,
        evidence_caveats: &["Only tracks files opened via common dialog; programmatic access not recorded"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Updated per file open; fixed max MRU depth",
    },
    ArtifactProfile {
        id: "recycle_bin",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["File name and deletion time available; original content may be overwritten"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Deleted on permanent delete; survives recycle until purge",
    },
    ArtifactProfile {
        id: "shellbags_user",
        evidence_strength: EvidenceStrength::Corroborative,
        evidence_caveats: &["Proves folder was browsed; does not prove file access or execution"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Updated on folder access; persists in UsrClass.dat",
    },
    ArtifactProfile {
        id: "usn_journal",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Circular; entries overwritten; may not have full history"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Circular journal; oldest entries overwritten first",
    },
    ArtifactProfile {
        id: "srum_app_resource",
        evidence_strength: EvidenceStrength::Corroborative,
        evidence_caveats: &[
            "CPU and memory usage metrics; useful for corroborating execution, not proving it",
        ],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "SRUM ESE database; rotated by Windows on schedule",
    },
    ArtifactProfile {
        id: "mft",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Requires raw disk access or volume shadow copy; locked on live systems",
            "SI timestamps are user-spoofable; always compare against FN timestamps",
            "Deleted-file entries may be overwritten if MFT fills up",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "$MFT entries persist until overwritten by new allocations; unallocated entries survive long-term",
    },
    ArtifactProfile {
        id: "usnjrnl",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &[
            "Journal is a rolling window (~32 MB default); older entries are overwritten",
            "Journal can be cleared by an attacker with sufficient privileges",
            "$J alternate data stream requires raw NTFS access — not visible via Win32 APIs",
        ],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "$UsnJrnl:$J is a rolling window (~32 MB); oldest records are overwritten as the journal grows",
    },
    ArtifactProfile {
        id: "logfile_ntfs",
        evidence_strength: EvidenceStrength::Corroborative,
        evidence_caveats: &[
            "~64 MB rolling window; typically only hours of recent metadata operations",
            "Primarily useful for cross-validating MFT LSN chains to detect timestamp injection",
            "Requires specialised NTFS log parser (e.g. NTFSLogTracker)",
        ],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "$LogFile is ~64 MB; wraps on high-activity systems within hours",
    },
    ArtifactProfile {
        id: "srum_db",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &[
            "Requires ESE database parsing; data is aggregated over time windows",
            "App paths may be partial; correlate with other execution artifacts",
        ],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "SRUM ESE database; records rolled up and purged periodically",
    },
    ArtifactProfile {
        id: "srum_network_usage",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &[
            "Aggregated bytes sent/received per process; not per-connection detail",
            "Clock skew between SRUM and event logs possible",
        ],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "SRUM network table; rotated by Windows on schedule",
    },
    ArtifactProfile {
        id: "network_drives",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Mapped drive destinations reveal lateral movement targets; UNC paths may expose internal host names"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Mapped drive registry entry; persists until unmapped",
    },
    ArtifactProfile {
        id: "networklist_profiles",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Profile name set by router; can be spoofed by attacker-controlled AP"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Network profiles persist in registry",
    },
    ArtifactProfile {
        id: "rdp_client_servers",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Proves RDP was initiated FROM this machine; does not confirm success"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "MRU; rotated when max entries exceeded",
    },
    ArtifactProfile {
        id: "wifi_profiles",
        evidence_strength: EvidenceStrength::Corroborative,
        evidence_caveats: &["Network profile history shows locations visited; useful for timeline and geographic profiling"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "WiFi profiles persist in registry until deleted",
    },
    ArtifactProfile {
        id: "evtx_powershell",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Requires script block logging to be enabled (4104)",
            "AMSI bypass can prevent logging of obfuscated content",
        ],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Circular EVTX log; oldest events overwritten at max size",
    },
    ArtifactProfile {
        id: "evtx_security",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Log can be cleared (event 1102/104); absence of log is itself evidence",
            "Requires appropriate audit policy to be enabled",
        ],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Circular EVTX log; default 128 MB max",
    },
    ArtifactProfile {
        id: "evtx_sysmon",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Requires Sysmon to be installed and configured",
            "Sysmon config determines what is logged",
        ],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Circular EVTX log; size depends on Sysmon config",
    },
    ArtifactProfile {
        id: "evtx_system",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Service install/start events useful; can be noisy with false positives"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Circular EVTX log; default 20 MB max",
    },
    ArtifactProfile {
        id: "linux_auth_log",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["rsyslog/syslog-ng must be running; can be cleared by root"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "logrotate weekly by default",
    },
    ArtifactProfile {
        id: "linux_bash_history",
        evidence_strength: EvidenceStrength::Circumstantial,
        evidence_caveats: &[
            "Trivially disabled with HISTSIZE=0 or HISTFILE=/dev/null",
            "Written at shell exit; killed shells leave no history",
            "Root can modify or delete",
        ],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Written at shell exit; max HISTSIZE entries",
    },
    ArtifactProfile {
        id: "linux_chrome_login_linux",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "On Linux, Chrome uses GNOME Keyring or KWallet for encryption key storage",
            "Plaintext accessible if keyring is unlocked",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SQLite DB; credentials persist until deleted from browser",
    },
    ArtifactProfile {
        id: "linux_firefox_logins_linux",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Same format as Windows Firefox logins; key4.db required for decryption",
            "Primary password prevents access if set",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "JSON file; credentials persist until deleted from browser",
    },
    ArtifactProfile {
        id: "linux_gnome_keyring",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Encrypted with user login password; accessible after user session unlock",
            "Contains Wi-Fi keys, VPN credentials, and application secrets",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Keyring database file; persists until secrets removed",
    },
    ArtifactProfile {
        id: "linux_kde_kwallet",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Encrypted; requires wallet password or auto-unlock to access",
            "Coverage depends on which KDE applications store credentials here",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "KWallet database file; persists until secrets removed",
    },
    ArtifactProfile {
        id: "linux_passwd",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "World-readable; shows all accounts but no password hashes (those are in shadow)",
            "Added accounts may be backdoors; compare against baseline",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "File; persists until account deleted",
    },
    ArtifactProfile {
        id: "linux_shadow",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Requires root to read; contains hashed passwords",
            "Hash format determines crackability; check for weak algorithms (MD5, SHA-256)",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "File; persists until account deleted or password changed",
    },
    ArtifactProfile {
        id: "linux_ssh_private_key",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Private key presence proves capability for lateral movement",
            "Passphrase-protected keys require cracking; unprotected keys are immediately usable",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "File; persists until explicitly removed",
    },
    ArtifactProfile {
        id: "linux_sudoers_d",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &[
            "Presence of unexpected rules is high-confidence privilege escalation indicator",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Files in /etc/sudoers.d/; persist until explicitly removed",
    },
    ArtifactProfile {
        id: "linux_journal_dir",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["systemd journal provides structured authentication and system events; requires journalctl for parsing"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "systemd journal; rotated by journald size/time limits",
    },
    ArtifactProfile {
        id: "linux_user_crontab",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Unexpected cron entries are definitive persistence indicators; compare against known-good baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Crontab entry; persists until crontab -r",
    },
    ArtifactProfile {
        id: "linux_wtmp",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Binary format; utmpdump needed; can be edited by root"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Rotated by logrotate",
    },
    ArtifactProfile {
        id: "macos_launch_agents_user",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &[
            "LaunchAgent plists in ~/Library/LaunchAgents prove user-context persistence",
            "Legitimate software also uses LaunchAgents; cross-reference signing and bundle ID",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "LaunchAgent plist persists until deleted; survives reboots",
    },
    ArtifactProfile {
        id: "macos_launch_agents_system",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &[
            "System LaunchAgents require root installation; elevated-privilege persistence indicator",
            "Apple-signed plists are expected; unsigned or ad-hoc signed warrant investigation",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "System-wide LaunchAgent plist; requires root to modify",
    },
    ArtifactProfile {
        id: "macos_launch_daemons",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &[
            "LaunchDaemons run as root; highest-privilege persistence mechanism on macOS",
            "Correlate with install history and Gatekeeper records for origin attribution",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "LaunchDaemon plist; persists across reboots, requires root",
    },
    ArtifactProfile {
        id: "macos_keychain_user",
        evidence_strength: EvidenceStrength::Corroborative,
        evidence_caveats: &[
            "Keychain DB requires user unlock; credential entries show what accounts were stored",
            "Cannot be read without unlocking; useful post-acquisition with user password",
        ],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Keychain DB; persists until item deletion or keychain reset",
    },
    ArtifactProfile {
        id: "mem_running_processes",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Live RAM only; requires active acquisition"],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "RAM; lost on power-off",
    },
    ArtifactProfile {
        id: "mem_network_connections",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Volatile; connections may close during acquisition"],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "RAM; lost on power-off",
    },
    ArtifactProfile {
        id: "mem_loaded_modules",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Live RAM only; requires active acquisition; unlisted modules indicate injection"],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "RAM; lost on power-off",
    },
    ArtifactProfile {
        id: "mem_registry_hives",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Live RAM only; in-memory hive state may differ from on-disk"],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "RAM; lost on power-off",
    },
    ArtifactProfile {
        id: "mem_user_credentials",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Credentials in memory (LSASS); most valuable live artifact"],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "RAM; lost on power-off",
    },
    ArtifactProfile {
        id: "credential_providers",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Registry key; may be modified by legitimate security products"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persistent until deleted",
    },
    ArtifactProfile {
        id: "scheduled_task_registry_cache",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Survives XML task file deletion; high-fidelity persistence evidence"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry cache; survives XML task file deletion",
    },
    ArtifactProfile {
        id: "winlogon_notify",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Obsolete on Vista+; presence itself is highly suspicious"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persistent until deleted",
    },
    ArtifactProfile {
        id: "usb_stor_enum",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Device serial numbers persist; device may have been removed"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; survives device removal",
    },
    ArtifactProfile {
        id: "setupapi_dev_log",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["First connection timestamps are reliable; log may be cleared"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Log file; retained until manually cleared",
    },
    ArtifactProfile {
        id: "terminal_server_client_servers_ext",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Reveals UsernameHint used for RDP — near-definitive lateral movement evidence"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persists across sessions",
    },
    ArtifactProfile {
        id: "evtx_task_scheduler",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Event log; may be cleared by attackers"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log; rotated on size limit",
    },
    ArtifactProfile {
        id: "evtx_rdp_client",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Outbound RDP; proves this host pivoted to another"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log; rotated on size limit",
    },
    ArtifactProfile {
        id: "evtx_rdp_inbound",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["1149 events confirm source IP before session; not easily faked"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log; rotated on size limit",
    },
    ArtifactProfile {
        id: "evtx_rdp_session",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Session lifecycle with timestamps; event 39 = RDP hijack"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log; rotated on size limit",
    },
    ArtifactProfile {
        id: "evtx_winrm",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Confirms PowerShell Remoting lateral movement with account"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log; rotated on size limit",
    },
    ArtifactProfile {
        id: "evtx_wmi_activity",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["5861 = permanent WMI subscription — near-certain persistence"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log; rotated on size limit",
    },
    ArtifactProfile {
        id: "evtx_defender",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Detection events survive file deletion; tamper events are highly suspicious"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log; rotated on size limit",
    },
    ArtifactProfile {
        id: "evtx_netlogon",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["5827/5828 = ZeroLogon exploitation attempt — very low false-positive rate"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log; rotated on size limit",
    },
    ArtifactProfile {
        id: "evtx_lsa_protection",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["PPL changes indicate credential dumping preparation"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log; rotated on size limit",
    },
    ArtifactProfile {
        id: "macos_fsevents",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Kernel-level; not easily tampered; covers all file system activity"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "FSEvents log; rotated as volume fills",
    },
    ArtifactProfile {
        id: "macos_login_items_plist",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Persistence mechanism; SFL2 format varies by OS version"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Plist file; persistent until deleted",
    },
    ArtifactProfile {
        id: "macos_tcc_system_db",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["System-wide privacy permissions; requires SIP bypass to tamper"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SQLite DB; persistent until reset",
    },
    ArtifactProfile {
        id: "macos_sms_db",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["iMessage/SMS content; may be partially encrypted or unavailable without cloud sync"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SQLite DB; persistent until deleted",
    },
    ArtifactProfile {
        id: "linux_auditd_log",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Kernel-level syscall auditing; attacker must disable auditd to evade"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Log file; rotated by logrotate",
    },
    ArtifactProfile {
        id: "linux_secure_log",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Authentication events; quality depends on PAM configuration"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Log file; rotated by logrotate",
    },
    ArtifactProfile {
        id: "linux_apache_access_log",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Web exploitation primary source; attacker may delete or tamper"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Log file; rotated by logrotate",
    },
    ArtifactProfile {
        id: "linux_nginx_access_log",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Web exploitation primary source; attacker may delete or tamper"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Log file; rotated by logrotate",
    },
    ArtifactProfile {
        id: "linux_selinux_config",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Disabled SELinux is itself a strong indicator of attacker activity"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Config file; persistent until modified",
    },
    ArtifactProfile {
        id: "linux_proc_modules",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Live kernel modules; rootkit detection; lost on reboot"],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "Virtual FS; lost on reboot",
    },
    ArtifactProfile {
        id: "winlogon_autoadmin_logon",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Legitimate on unattended kiosk/server builds; verify DefaultPassword also present"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry value; persistent until modification",
    },
    ArtifactProfile {
        id: "winlogon_default_password",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Presence proves plaintext credential stored; must confirm AutoAdminLogon=1 for context"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry value; persistent until modification",
    },
    ArtifactProfile {
        id: "portproxy_config",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Legitimate uses exist (e.g., WSL2 port forwarding); verify rule targets are suspicious"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persistent until netsh portproxy delete",
    },
    ArtifactProfile {
        id: "windows_defender_exclusions_local",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Legitimate AV exclusions common; suspicious if path matches known attacker staging directories"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persistent until Defender policy change",
    },
    ArtifactProfile {
        id: "windows_defender_disabled_av",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Via policy key — Tamper Protection bypass required; near-certain indicator of deliberate disabling"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry value; persistent until GPO refresh",
    },
    ArtifactProfile {
        id: "windows_defender_realtime",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Individual component flags may be legitimately set by MDM; check for combination of multiple disabled components"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persistent until Defender reset",
    },
    ArtifactProfile {
        id: "ms_office_trusted_docs",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Legitimate macros also create entries; suspicious if document path is temp folder or remote share"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Updated when user enables Office document macros",
    },
    ArtifactProfile {
        id: "vss_files_not_to_snapshot",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Non-Microsoft entries in this key are highly suspicious; verify against known software"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persistent until registry modification",
    },
    ArtifactProfile {
        id: "vss_files_not_to_backup",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Non-Microsoft entries in this key are highly suspicious; verify against known software"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persistent until registry modification",
    },
    ArtifactProfile {
        id: "ifeo_silent_exit",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Legitimate uses exist (WER config); suspicious if MonitorProcess points to unknown binary"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persistent until modification",
    },
    ArtifactProfile {
        id: "exefile_shell_open_software",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Any deviation from default (%1 %*) is extremely suspicious; near-certain compromise indicator"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry value; persistent until explicit deletion",
    },
    ArtifactProfile {
        id: "exefile_shell_open_usrclass",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Any presence of this key is suspicious; no legitimate software sets per-user .exe handler"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "UsrClass.dat value; persistent until profile deletion",
    },
    ArtifactProfile {
        id: "rdp_shadow_sessions",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Shadow=2 or 4 (no consent) is particularly suspicious; verify against admin policy"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry value; persistent until policy modification",
    },
    ArtifactProfile {
        id: "restricted_admin_rdp",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["May be legitimately enabled for privileged access workstations; context required"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry value; persistent until explicit change",
    },
    ArtifactProfile {
        id: "network_shares_server",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Legitimate shares common; suspicious if share path is attacker staging directory or C: root"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persistent until share removal",
    },
    ArtifactProfile {
        id: "ms_office_server_cache",
        evidence_strength: EvidenceStrength::Corroborative,
        evidence_caveats: &["URL presence requires correlation with known C2 domains; many legitimate Office URLs expected"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Updated on Office server connections; persists in NTUSER.DAT",
    },
    ArtifactProfile {
        id: "powershell_cobalt_info",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Key is not created by legitimate software; presence is near-certain Cobalt Strike IOC"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key created by Cobalt Strike; persistent until cleanup",
    },
    ArtifactProfile {
        id: "taskcache_tasks_path",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Many legitimate tasks present; suspicious tasks have random names or reside outside \\Microsoft\\"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persistent until task deletion",
    },
    ArtifactProfile {
        id: "event_log_channel_status",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Disabled Security or Sysmon channel during an incident is near-certain evidence of tampering"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key; persistent until channel re-enabled",
    },
    ArtifactProfile {
        id: "chrome_history",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["History may be cleared; private browsing not recorded; timestamps are WebKit microseconds requiring conversion"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Overwritten by browser activity; no size limit",
    },
    ArtifactProfile {
        id: "edge_chromium_history",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Same caveats as Chrome History; profile switching means not all activity in default profile"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Overwritten by browser activity; no size limit",
    },
    ArtifactProfile {
        id: "edge_chromium_login_data",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["DPAPI encryption requires user context or masterkey to decrypt; credential presence proves account storage"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Persists until credential explicitly removed",
    },
    ArtifactProfile {
        id: "firefox_places",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["History may be manually cleared; private browsing not recorded; frecency scoring can obscure visit count accuracy"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Overwritten by browser activity; no size limit",
    },
    ArtifactProfile {
        id: "psreadline_history",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["User can manually edit or clear file; oldest entries evicted at limit; does not capture non-interactive PS sessions"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Oldest lines evicted at 4096-line limit",
    },
    ArtifactProfile {
        id: "psreadline_history_system",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Only populated when SYSTEM runs interactive PS; many SYSTEM PS sessions are non-interactive"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Oldest lines evicted at 4096-line limit",
    },
    ArtifactProfile {
        id: "powershell_transcripts",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Requires transcript policy to be enabled; attacker may disable policy before activity"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Accumulate indefinitely; not auto-rotated",
    },
    ArtifactProfile {
        id: "teamviewer_connection_log",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["File may be deleted by attacker; timestamps correlate with partner ID that can be traced to account"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Appended per session; not auto-cleared",
    },
    ArtifactProfile {
        id: "anydesk_trace_user",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Rotated at size limit; attacker may clear ad.trace; session IDs in log can be used to request records from AnyDesk"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Rotated at size limit; .old retains previous",
    },
    ArtifactProfile {
        id: "anydesk_trace_system",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Only present when AnyDesk installed as service; may be absent on per-user installs"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Rotated at size limit",
    },
    ArtifactProfile {
        id: "anydesk_connection_trace",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Structured format; attacker cleanup often misses this file; contains both inbound and outbound connections"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Appended; grows until manually cleared",
    },
    ArtifactProfile {
        id: "anydesk_file_transfer_log",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Proves exfiltration direction and filename; attacker cleanup often misses this file"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Appended; grows until manually cleared",
    },
    ArtifactProfile {
        id: "screenconnect_session_db",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Only present on self-hosted deployments; cloud-hosted sessions leave no local DB"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SQLite DB; retained until manually cleared",
    },
    ArtifactProfile {
        id: "dropbox_instance_db",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Requires Dropbox-specific SQLite parser (obfuscated schema); file hashes prove sync without local copy"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SQLite DB; persists until Dropbox uninstalled",
    },
    ArtifactProfile {
        id: "onedrive_metadata",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["ODL log parsing complex; SyncEngineDatabase.db reveals cloud-only placeholders — strongest exfil evidence"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SQLite DB; persists; ODL logs rotate",
    },
    ArtifactProfile {
        id: "google_drive_fs_metadata",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["metadata.db schema may change between Drive for Desktop versions; requires version-appropriate parser"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SQLite DB; persists until Drive uninstalled",
    },
    ArtifactProfile {
        id: "teams_indexed_db",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["LevelDB parsing requires specialized tooling; data may be encrypted at rest on newer Teams versions"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "LevelDB cache; grows with Teams usage",
    },
    ArtifactProfile {
        id: "slack_indexed_db",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["LevelDB format; workspace data may be partially encrypted; availability depends on Slack plan retention settings"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "LevelDB cache; grows with Slack usage",
    },
    ArtifactProfile {
        id: "discord_local_storage",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Token extraction may require memory analysis; Discord rotates tokens on detection; LevelDB parsing required"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Persists until Discord uninstalled or cleared",
    },
    ArtifactProfile {
        id: "signal_database",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["SQLCipher encrypted; requires config.json key to decrypt; without key, message content is inaccessible"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SQLCipher SQLite; persists until user deletes",
    },
    ArtifactProfile {
        id: "signal_config_json",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Contains plaintext decryption key; any process with user access can decrypt all Signal messages"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Regenerated only on fresh install; otherwise permanent",
    },
    ArtifactProfile {
        id: "certutil_cache",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Hash-named files require external resolution; creation timestamp = download time; survives downloaded file deletion"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "CryptNet cache; persists until explicitly flushed",
    },
    ArtifactProfile {
        id: "sdb_custom_files",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Any .sdb file here is legitimately rare; requires sdbinst.exe or direct file copy — both leave evidence"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Installed SDB files persist until explicitly removed",
    },
    ArtifactProfile {
        id: "iis_w3svc_logs",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Attacker may clear logs; Managed Pipeline may not log all requests; X-Forwarded-For spoofing common"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Rotated daily; retention per IIS config",
    },
    ArtifactProfile {
        id: "iis_config_applicationhost",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Handler additions persist until config reset; embedded webshell paths in handlers are definitive indicators"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Persistent IIS config; modified by admin or attacker",
    },
    ArtifactProfile {
        id: "dns_debug_log",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Requires debug logging to be enabled; attacker may disable to evade; single-file rotation can overwrite evidence"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Single file rotated at configured size limit",
    },
    ArtifactProfile {
        id: "sum_db",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Windows Server only; requires ESE/JET parser; timestamps in local server time — convert to UTC"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Up to 2 years retention; rolled annually",
    },
    ArtifactProfile {
        id: "copilot_recall_ukg",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Requires Copilot+ hardware with Recall enabled; VBS/PPLA protects live DB; accessible from acquired image"],
        volatility: VolatilityClass::ActivityDriven,
        volatility_rationale: "Rolling 90-day window; older screenshots purged",
    },
    ArtifactProfile {
        id: "ntuser_dat_file",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Single hive provides all HKCU artifacts; transaction logs (.LOG1/.LOG2) must be applied for current state"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Exists for lifetime of user profile",
    },
    ArtifactProfile {
        id: "active_setup",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Rogue sub-key presence is definitive; compare StubPath against known-good baseline; last-write time indicates installation"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key persists until explicitly deleted",
    },
    ArtifactProfile {
        id: "lsa_auth_packages",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Any non-msv1_0 DLL is definitive IOC; requires reboot to activate; compare against Windows baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry value persists across reboots; requires reboot to take effect",
    },
    ArtifactProfile {
        id: "lsa_security_packages",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Any non-Microsoft SSP DLL is definitive IOC; cross-reference DLL hash with threat intel"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry value persists across reboots; requires reboot to take effect",
    },
    ArtifactProfile {
        id: "print_monitor_dlls",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Rogue Driver value in any sub-key is definitive; PrintNightmare (CVE-2021-1675) may leave forensic artifacts"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key persists until explicitly deleted",
    },
    ArtifactProfile {
        id: "services_hklm",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["New service sub-key creation time is definitive; ImagePath outside System32/SysWOW64 is suspicious; correlate with EVTX 7045"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key persists until service key deletion",
    },
    ArtifactProfile {
        id: "browsers_firefox_logins",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted browser passwords; key in OS credential store; timestamp shows last use"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Credential store persists until browser profile deletion",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_networksecurity_debug",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_smbclient_security",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_smbserver_security",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_adminless_operational",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_audit_configuration_client_d",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_audit_configuration_client_o",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_configuration_wizard_diagnos",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_configuration_wizard_operati",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_enterprisedata_filerevocatio",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_exchangeactivesyncprovisioni",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_identitystore_performance",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_lessprivilegedappcontainer_o",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_licensing_slc_perf",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_netlogon_operational",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_spp_ux_gc_analytic",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_spp_ux_genuinecenter_logging",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_spp_ux_notifications_actionc",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_spp_ux_analytic",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_spp_perf",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_userconsentverifier_audit",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_security_vault_performance",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_securitymitigationsbroker_perf",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_securitymitigationsbroker_operational",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "evtx_microsoft_windows_securitymitigationsbroker_admin",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Windows Security audit log; check Policy log for channel disable events"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Event log rotates on size limit; Security channel is high-value",
    },
    ArtifactProfile {
        id: "fa_file_log_esxtokend_log",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Authentication events to vSphere; check for admin API token theft"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "ESXi token daemon log persists until rotation",
    },
    ArtifactProfile {
        id: "fa_file_etc_passwd",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Check for UID 0 accounts not root; compare shadow file for password hash presence"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "User account file persists until system decommission",
    },
    ArtifactProfile {
        id: "fa_file_kernel_dmesg_restrict",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Tampered value (0=off) indicates attacker hardening-bypass; check sysctl.conf"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Kernel sysctl setting persists across reboots when configured",
    },
    ArtifactProfile {
        id: "fa_file_kernel_kptr_restrict",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Tampered value (0=off) indicates attacker hardening-bypass; check sysctl.conf"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Kernel sysctl setting persists across reboots when configured",
    },
    ArtifactProfile {
        id: "fa_file_users_plist",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Check for UID 0 accounts not root; compare shadow file for password hash presence"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "User account file persists until system decommission",
    },
    ArtifactProfile {
        id: "fa_file_users_plist_2",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Check for UID 0 accounts not root; compare shadow file for password hash presence"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "User account file persists until system decommission",
    },
    ArtifactProfile {
        id: "fa_file_conf_tomcat_users_xml",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Plaintext credentials; check for admin-role accounts not in baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Tomcat credential file persists until application reconfiguration",
    },
    ArtifactProfile {
        id: "fa_file_conf_tomcat_users_xml_2",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Plaintext credentials; check for admin-role accounts not in baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Tomcat credential file persists until application reconfiguration",
    },
    ArtifactProfile {
        id: "fa_file_conf_tomcat_users_xml_3",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Plaintext credentials; check for admin-role accounts not in baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Tomcat credential file persists until application reconfiguration",
    },
    ArtifactProfile {
        id: "fa_file_conf_tomcat_users_xml_4",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Plaintext credentials; check for admin-role accounts not in baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Tomcat credential file persists until application reconfiguration",
    },
    ArtifactProfile {
        id: "fa_file_conf_tomcat_users_xml_5",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Plaintext credentials; check for admin-role accounts not in baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Tomcat credential file persists until application reconfiguration",
    },
    ArtifactProfile {
        id: "fa_file_conf_tomcat_users_xml_6",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Plaintext credentials; check for admin-role accounts not in baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Tomcat credential file persists until application reconfiguration",
    },
    ArtifactProfile {
        id: "fa_file_conf_tomcat_users_xml_7",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Plaintext credentials; check for admin-role accounts not in baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Tomcat credential file persists until application reconfiguration",
    },
    ArtifactProfile {
        id: "fa_file_conf_tomcat_users_xml_8",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Plaintext credentials; check for admin-role accounts not in baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Tomcat credential file persists until application reconfiguration",
    },
    ArtifactProfile {
        id: "fa_file_conf_tomcat_users_xml_9",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Plaintext credentials; check for admin-role accounts not in baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Tomcat credential file persists until application reconfiguration",
    },
    ArtifactProfile {
        id: "fa_file_conf_tomcat_users_xml_10",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Plaintext credentials; check for admin-role accounts not in baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Tomcat credential file persists until application reconfiguration",
    },
    ArtifactProfile {
        id: "fa_file_conf_tomcat_users_xml_11",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Plaintext credentials; check for admin-role accounts not in baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Tomcat credential file persists until application reconfiguration",
    },
    ArtifactProfile {
        id: "fa_file_ntds_ntds_dit",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Domain credential store; offline cracking risk; compare hash count against user count"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Active Directory database persists until DC decommission",
    },
    ArtifactProfile {
        id: "fa_file_ntds_dit",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Domain credential store; offline cracking risk; compare hash count against user count"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Active Directory database persists until DC decommission",
    },
    ArtifactProfile {
        id: "fa_file_ntds_dit_2",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Domain credential store; offline cracking risk; compare hash count against user count"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Active Directory database persists until DC decommission",
    },
    ArtifactProfile {
        id: "fa_file_system32_ntds_dit",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Domain credential store; offline cracking risk; compare hash count against user count"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Active Directory database persists until DC decommission",
    },
    ArtifactProfile {
        id: "fa_authentication_credential_provider_filters",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Non-default DLLs indicate credential interception; compare against known-good baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key persists until key deletion",
    },
    ArtifactProfile {
        id: "fa_authentication_credential_provider_filters_2",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Non-default DLLs indicate credential interception; compare against known-good baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key persists until key deletion",
    },
    ArtifactProfile {
        id: "fa_authentication_credential_providers",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Non-default DLLs indicate credential interception; compare against known-good baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key persists until key deletion",
    },
    ArtifactProfile {
        id: "fa_authentication_credential_providers_2",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Non-default DLLs indicate credential interception; compare against known-good baseline"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Registry key persists until key deletion",
    },
    ArtifactProfile {
        id: "kape_file_1password_data_1password10_sqlite",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted browser passwords; key in OS credential store; timestamp shows last use"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Credential store persists until browser profile deletion",
    },
    ArtifactProfile {
        id: "kape_file_1password_backups_1password10_sqlite",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted browser passwords; key in OS credential store; timestamp shows last use"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Credential store persists until browser profile deletion",
    },
    ArtifactProfile {
        id: "kape_file_1password_logs_log",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted browser passwords; key in OS credential store; timestamp shows last use"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Credential store persists until browser profile deletion",
    },
    ArtifactProfile {
        id: "kape_file_aws_credentials",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["AWS access key ID and secret; timestamp indicates when last modified"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Credential file persists until key rotation",
    },
    ArtifactProfile {
        id: "kape_file_user_git_credentials",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Repository tokens; check for non-corporate VCS hosts"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Git credential helper store persists until credential deletion",
    },
    ArtifactProfile {
        id: "kape_file_free_download_manager_fdm_sqlite",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["May contain saved FTP/HTTP credentials; check for non-standard download sources"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Download manager credential database persists until uninstall",
    },
    ArtifactProfile {
        id: "kape_file_my_certificates",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Personal certificates including private keys; check for self-signed or unexpected issuers"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Certificate store persists until certificate deletion",
    },
    ArtifactProfile {
        id: "kape_file_logins_json",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted browser passwords; key in OS credential store; timestamp shows last use"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Credential store persists until browser profile deletion",
    },
    ArtifactProfile {
        id: "kape_file_mremoteng_confcons_xml",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted vault; master password hash extractable for offline attack"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Password manager database persists until application uninstall",
    },
    ArtifactProfile {
        id: "kape_file_key_db",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted vault; master password hash extractable for offline attack"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Password manager database persists until application uninstall",
    },
    ArtifactProfile {
        id: "kape_file_signon",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted browser passwords; key in OS credential store; timestamp shows last use"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Credential store persists until browser profile deletion",
    },
    ArtifactProfile {
        id: "kape_file_logins_json_2",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted browser passwords; key in OS credential store; timestamp shows last use"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Credential store persists until browser profile deletion",
    },
    ArtifactProfile {
        id: "kape_file_password_xp",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted browser passwords; key in OS credential store; timestamp shows last use"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Credential store persists until browser profile deletion",
    },
    ArtifactProfile {
        id: "kape_file_signon_2",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted browser passwords; key in OS credential store; timestamp shows last use"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Credential store persists until browser profile deletion",
    },
    ArtifactProfile {
        id: "kape_file_logins_json_2_2",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted browser passwords; key in OS credential store; timestamp shows last use"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Credential store persists until browser profile deletion",
    },
    ArtifactProfile {
        id: "kape_file_local_puffinsecurebrowserpasswordforms_dat",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted browser passwords; key in OS credential store; timestamp shows last use"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Credential store persists until browser profile deletion",
    },
    ArtifactProfile {
        id: "kape_file_local_puffinsecurebrowsercredential_dat",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Browser-saved form passwords; check timestamp against incident window"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Browser credential file persists until app data deletion",
    },
    ArtifactProfile {
        id: "kape_file_windows_ntds",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Domain credential store; offline cracking risk; compare hash count against user count"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Active Directory database persists until DC decommission",
    },
    ArtifactProfile {
        id: "kape_file_config_sam_log",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Local account credential hashes; NTLM offline cracking risk"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SAM hive persists across reboots; protected in-use by Windows",
    },
    ArtifactProfile {
        id: "kape_file_sam_registry_transac",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Verify presence against incident timeline; correlate with other triage artifacts"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Artifact persists until explicit deletion",
    },
    ArtifactProfile {
        id: "kape_file_config_sam",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Local account credential hashes; NTLM offline cracking risk"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SAM hive persists across reboots; protected in-use by Windows",
    },
    ArtifactProfile {
        id: "kape_file_sam_registry_hive",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Local account credential hashes; NTLM offline cracking risk"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SAM hive persists across reboots; protected in-use by Windows",
    },
    ArtifactProfile {
        id: "kape_file_regback_sam",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Verify presence against incident timeline; correlate with other triage artifacts"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Artifact persists until explicit deletion",
    },
    ArtifactProfile {
        id: "kape_file_sam_registry_hive_re",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Local account credential hashes; NTLM offline cracking risk"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SAM hive persists across reboots; protected in-use by Windows",
    },
    ArtifactProfile {
        id: "nirsoft_network_passwords_cred_dir",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Encrypted browser passwords; key in OS credential store; timestamp shows last use"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Credential store persists until browser profile deletion",
    },
    ArtifactProfile {
        id: "nirsoft_sam_hive_reg",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Local account credential hashes; NTLM offline cracking risk"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SAM hive persists across reboots; protected in-use by Windows",
    },
    ArtifactProfile {
        id: "regedit_domains_account_users",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Local account enumeration via registry; compare against expected user list"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SAM account registry persists until account deletion",
    },
    ArtifactProfile {
        id: "velociraptor_file_log_auth_log",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Authentication events; check for brute-force patterns and privilege escalation"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Linux log rotates on size/time schedule",
    },
    ArtifactProfile {
        id: "velociraptor_file_syslogtimestamp_timestamp_syslogfacility_s",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Authentication events; check for brute-force patterns and privilege escalation"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Linux log rotates on size/time schedule",
    },
    ArtifactProfile {
        id: "velociraptor_file_ssh_pem_id_rsa_id_dsa",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Private key presence proves access capability; verify authorized_keys for lateral movement"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Private key files persist until explicitly deleted",
    },
    ArtifactProfile {
        id: "velociraptor_file_usr",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Modified timestamps on system binaries indicate trojanized files"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "System binary directory persists until package update",
    },
    ArtifactProfile {
        id: "velociraptor_file_tmp_collection_zip",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Presence indicates active Velociraptor collection; metadata reveals scope"],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "Temporary collection ZIP is volatile and deleted after upload",
    },
    ArtifactProfile {
        id: "velociraptor_file_logs_security_evtx",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Velociraptor-collected EVTX; check collection timestamp vs log timespan"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Collected EVTX rotates; velociraptor copy is point-in-time",
    },
    ArtifactProfile {
        id: "velociraptor_file_logs_microsoft_windows_taskscheduler_4oper",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Scheduled task execution; correlate with persistence keys"],
        volatility: VolatilityClass::RotatingBuffer,
        volatility_rationale: "Task scheduler log rotates; collected copy is point-in-time",
    },
    ArtifactProfile {
        id: "velociraptor_file_config_sam",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Local account credential hashes; NTLM offline cracking risk"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "SAM hive persists across reboots; protected in-use by Windows",
    },
    ArtifactProfile {
        id: "velociraptor_currentversion_image_file_execution_options",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Non-zero GlobalFlag with Debugger value indicates silent process exit / hijack"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "IFEO GlobalFlag registry persists until key deletion",
    },
    ArtifactProfile {
        id: "velociraptor_securityproviders_wdigest",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["UseLogonCredential=1 enables plaintext credential caching in LSASS — critical IOC"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "WDigest registry value persists across reboots",
    },
    ArtifactProfile {
        id: "velociraptor_currentversion_profilelist",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["User SID enumeration; compare against expected user base for rogue accounts"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "ProfileList registry persists until profile deletion",
    },
    ArtifactProfile {
        id: "linux_lsof_output",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Live-response only; deleted files visible only while process holds fd open"],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "Process state; lost on process exit or system reboot",
    },
    ArtifactProfile {
        id: "linux_ss_output",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Live-response only; C2 connections disappear on session teardown"],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "Socket table exists only while connections are active",
    },
    ArtifactProfile {
        id: "linux_chkrootkit_output",
        evidence_strength: EvidenceStrength::Corroborative,
        evidence_caveats: &["Rootkit may subvert chkrootkit itself; corroborate with memory forensics"],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "Assessment output; not persisted unless explicitly saved",
    },
    ArtifactProfile {
        id: "linux_dmesg_log",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Kernel ring buffer wraps; grab early in live response"],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "Ring buffer — overwritten as kernel emits new messages",
    },
    ArtifactProfile {
        id: "linux_proc_kallsyms",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Requires root; compare against expected module symbols to find injected code"],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "Reflects live kernel symbol table; changes if modules loaded/unloaded",
    },
    ArtifactProfile {
        id: "linux_proc_net_tcp",
        evidence_strength: EvidenceStrength::Definitive,
        evidence_caveats: &["Live socket table; grab immediately — C2 connections close on detection"],
        volatility: VolatilityClass::Volatile,
        volatility_rationale: "Kernel socket table; entries vanish on connection close",
    },
    ArtifactProfile {
        id: "amcache_driver",
        evidence_strength: EvidenceStrength::Strong,
        evidence_caveats: &["Records driver load time, not execution time; SHA1 hash allows reputation lookup"],
        volatility: VolatilityClass::Persistent,
        volatility_rationale: "Amcache hive persists on disk; survives reboot",
    },
];

/// Returns the combined profile for a given artifact ID, or `None` if unknown.
///
/// # Example
///
/// ```rust
/// use forensicnomicon::profile::profile_for;
/// use forensicnomicon::evidence::EvidenceStrength;
/// use forensicnomicon::volatility::VolatilityClass;
///
/// let p = profile_for("mft").unwrap();
/// assert_eq!(p.evidence_strength, EvidenceStrength::Definitive);
/// assert_eq!(p.volatility, VolatilityClass::Persistent);
/// ```
pub fn profile_for(artifact_id: &str) -> Option<&'static ArtifactProfile> {
    ARTIFACT_PROFILES.iter().find(|p| p.id == artifact_id)
}
